/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppRoleReadTokenTtlResponse
 */
export interface AppRoleReadTokenTtlResponse {
    /**
     * The initial ttl of the token to generate
     * @type {number}
     * @memberof AppRoleReadTokenTtlResponse
     */
    tokenTtl?: number;
}

/**
 * Check if a given object implements the AppRoleReadTokenTtlResponse interface.
 */
export function instanceOfAppRoleReadTokenTtlResponse(value: object): value is AppRoleReadTokenTtlResponse {
    return true;
}

export function AppRoleReadTokenTtlResponseFromJSON(json: any): AppRoleReadTokenTtlResponse {
    return AppRoleReadTokenTtlResponseFromJSONTyped(json, false);
}

export function AppRoleReadTokenTtlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRoleReadTokenTtlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tokenTtl': json['token_ttl'] == null ? undefined : json['token_ttl'],
    };
}

export function AppRoleReadTokenTtlResponseToJSON(json: any): AppRoleReadTokenTtlResponse {
    return AppRoleReadTokenTtlResponseToJSONTyped(json, false);
}

export function AppRoleReadTokenTtlResponseToJSONTyped(value?: AppRoleReadTokenTtlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token_ttl': value['tokenTtl'],
    };
}

