/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoogleCloudKmsConfigureKeyRequest
 */
export interface GoogleCloudKmsConfigureKeyRequest {
    /**
     * Maximum allowed crypto key version. If set to a positive value, key versions greater than the given value are not permitted to be used. If set to 0 or a negative value, there is no maximum key version.
     * @type {number}
     * @memberof GoogleCloudKmsConfigureKeyRequest
     */
    maxVersion?: number;
    /**
     * Minimum allowed crypto key version. If set to a positive value, key versions less than the given value are not permitted to be used. If set to 0 or a negative value, there is no minimum key version. This value only affects encryption/re-encryption, not decryption. To restrict old values from being decrypted, increase this value and then perform a trim operation.
     * @type {number}
     * @memberof GoogleCloudKmsConfigureKeyRequest
     */
    minVersion?: number;
}

/**
 * Check if a given object implements the GoogleCloudKmsConfigureKeyRequest interface.
 */
export function instanceOfGoogleCloudKmsConfigureKeyRequest(value: object): value is GoogleCloudKmsConfigureKeyRequest {
    return true;
}

export function GoogleCloudKmsConfigureKeyRequestFromJSON(json: any): GoogleCloudKmsConfigureKeyRequest {
    return GoogleCloudKmsConfigureKeyRequestFromJSONTyped(json, false);
}

export function GoogleCloudKmsConfigureKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleCloudKmsConfigureKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'maxVersion': json['max_version'] == null ? undefined : json['max_version'],
        'minVersion': json['min_version'] == null ? undefined : json['min_version'],
    };
}

export function GoogleCloudKmsConfigureKeyRequestToJSON(json: any): GoogleCloudKmsConfigureKeyRequest {
    return GoogleCloudKmsConfigureKeyRequestToJSONTyped(json, false);
}

export function GoogleCloudKmsConfigureKeyRequestToJSONTyped(value?: GoogleCloudKmsConfigureKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_version': value['maxVersion'],
        'min_version': value['minVersion'],
    };
}

