/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiConfigureKeysResponse
 */
export interface PkiConfigureKeysResponse {
    /**
     * Reference (name or identifier) to the default issuer.
     * @type {string}
     * @memberof PkiConfigureKeysResponse
     */
    _default?: string;
}

/**
 * Check if a given object implements the PkiConfigureKeysResponse interface.
 */
export function instanceOfPkiConfigureKeysResponse(value: object): value is PkiConfigureKeysResponse {
    return true;
}

export function PkiConfigureKeysResponseFromJSON(json: any): PkiConfigureKeysResponse {
    return PkiConfigureKeysResponseFromJSONTyped(json, false);
}

export function PkiConfigureKeysResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiConfigureKeysResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '_default': json['default'] == null ? undefined : json['default'],
    };
}

export function PkiConfigureKeysResponseToJSON(json: any): PkiConfigureKeysResponse {
    return PkiConfigureKeysResponseToJSONTyped(json, false);
}

export function PkiConfigureKeysResponseToJSONTyped(value?: PkiConfigureKeysResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default': value['_default'],
    };
}

