/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiIssuersImportCertRequest
 */
export interface PkiIssuersImportCertRequest {
    /**
     * PEM-format, concatenated unencrypted secret-key (optional) and certificates.
     * @type {string}
     * @memberof PkiIssuersImportCertRequest
     */
    pemBundle?: string;
}

/**
 * Check if a given object implements the PkiIssuersImportCertRequest interface.
 */
export function instanceOfPkiIssuersImportCertRequest(value: object): value is PkiIssuersImportCertRequest {
    return true;
}

export function PkiIssuersImportCertRequestFromJSON(json: any): PkiIssuersImportCertRequest {
    return PkiIssuersImportCertRequestFromJSONTyped(json, false);
}

export function PkiIssuersImportCertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiIssuersImportCertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pemBundle': json['pem_bundle'] == null ? undefined : json['pem_bundle'],
    };
}

export function PkiIssuersImportCertRequestToJSON(json: any): PkiIssuersImportCertRequest {
    return PkiIssuersImportCertRequestToJSONTyped(json, false);
}

export function PkiIssuersImportCertRequestToJSONTyped(value?: PkiIssuersImportCertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pem_bundle': value['pemBundle'],
    };
}

