/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse
 */
export interface PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse {
    /**
     * Certificate Chain
     * @type {Array<string>}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse
     */
    caChain?: Array<string>;
    /**
     * Certificate
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse
     */
    certificate?: string;
    /**
     * Time of expiration
     * @type {number}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse
     */
    expiration?: number;
    /**
     * Issuing Certificate Authority
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse
     */
    issuingCa?: string;
    /**
     * Serial Number
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse
     */
    serialNumber?: string;
}

/**
 * Check if a given object implements the PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse interface.
 */
export function instanceOfPkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse(value: object): value is PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse {
    return true;
}

export function PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponseFromJSON(json: any): PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse {
    return PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponseFromJSONTyped(json, false);
}

export function PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'caChain': json['ca_chain'] == null ? undefined : json['ca_chain'],
        'certificate': json['certificate'] == null ? undefined : json['certificate'],
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'issuingCa': json['issuing_ca'] == null ? undefined : json['issuing_ca'],
        'serialNumber': json['serial_number'] == null ? undefined : json['serial_number'],
    };
}

export function PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponseToJSON(json: any): PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse {
    return PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponseToJSONTyped(json, false);
}

export function PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponseToJSONTyped(value?: PkiWriteIssuerIssuerRefExternalPolicySignPolicyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ca_chain': value['caChain'],
        'certificate': value['certificate'],
        'expiration': value['expiration'],
        'issuing_ca': value['issuingCa'],
        'serial_number': value['serialNumber'],
    };
}

