/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiWriteIssuerIssuerRefExternalPolicyIssueResponse
 */
export interface PkiWriteIssuerIssuerRefExternalPolicyIssueResponse {
    /**
     * Certificate Chain
     * @type {Array<string>}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicyIssueResponse
     */
    caChain?: Array<string>;
    /**
     * Certificate
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicyIssueResponse
     */
    certificate?: string;
    /**
     * Time of expiration
     * @type {number}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicyIssueResponse
     */
    expiration?: number;
    /**
     * Issuing Certificate Authority
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicyIssueResponse
     */
    issuingCa?: string;
    /**
     * Private key
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicyIssueResponse
     */
    privateKey?: string;
    /**
     * Private key type
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicyIssueResponse
     */
    privateKeyType?: string;
    /**
     * Serial Number
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefExternalPolicyIssueResponse
     */
    serialNumber?: string;
}

/**
 * Check if a given object implements the PkiWriteIssuerIssuerRefExternalPolicyIssueResponse interface.
 */
export function instanceOfPkiWriteIssuerIssuerRefExternalPolicyIssueResponse(value: object): value is PkiWriteIssuerIssuerRefExternalPolicyIssueResponse {
    return true;
}

export function PkiWriteIssuerIssuerRefExternalPolicyIssueResponseFromJSON(json: any): PkiWriteIssuerIssuerRefExternalPolicyIssueResponse {
    return PkiWriteIssuerIssuerRefExternalPolicyIssueResponseFromJSONTyped(json, false);
}

export function PkiWriteIssuerIssuerRefExternalPolicyIssueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiWriteIssuerIssuerRefExternalPolicyIssueResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'caChain': json['ca_chain'] == null ? undefined : json['ca_chain'],
        'certificate': json['certificate'] == null ? undefined : json['certificate'],
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'issuingCa': json['issuing_ca'] == null ? undefined : json['issuing_ca'],
        'privateKey': json['private_key'] == null ? undefined : json['private_key'],
        'privateKeyType': json['private_key_type'] == null ? undefined : json['private_key_type'],
        'serialNumber': json['serial_number'] == null ? undefined : json['serial_number'],
    };
}

export function PkiWriteIssuerIssuerRefExternalPolicyIssueResponseToJSON(json: any): PkiWriteIssuerIssuerRefExternalPolicyIssueResponse {
    return PkiWriteIssuerIssuerRefExternalPolicyIssueResponseToJSONTyped(json, false);
}

export function PkiWriteIssuerIssuerRefExternalPolicyIssueResponseToJSONTyped(value?: PkiWriteIssuerIssuerRefExternalPolicyIssueResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ca_chain': value['caChain'],
        'certificate': value['certificate'],
        'expiration': value['expiration'],
        'issuing_ca': value['issuingCa'],
        'private_key': value['privateKey'],
        'private_key_type': value['privateKeyType'],
        'serial_number': value['serialNumber'],
    };
}

