/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest
 */
export interface PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest {
    /**
     * ACME request 'payload' value
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest
     */
    payload?: string;
    /**
     * ACME request 'protected' value
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest
     */
    _protected?: string;
    /**
     * ACME request 'signature' value
     * @type {string}
     * @memberof PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest
     */
    signature?: string;
}

/**
 * Check if a given object implements the PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest interface.
 */
export function instanceOfPkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest(value: object): value is PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest {
    return true;
}

export function PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequestFromJSON(json: any): PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest {
    return PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequestFromJSONTyped(json, false);
}

export function PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'payload': json['payload'] == null ? undefined : json['payload'],
        '_protected': json['protected'] == null ? undefined : json['protected'],
        'signature': json['signature'] == null ? undefined : json['signature'],
    };
}

export function PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequestToJSON(json: any): PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest {
    return PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequestToJSONTyped(json, false);
}

export function PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequestToJSONTyped(value?: PkiWriteIssuerIssuerRefAcmeOrderOrderIdFinalizeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payload': value['payload'],
        'protected': value['_protected'],
        'signature': value['signature'],
    };
}

