/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PluginsCatalogListPluginsResponse
 */
export interface PluginsCatalogListPluginsResponse {
    /**
     * 
     * @type {object}
     * @memberof PluginsCatalogListPluginsResponse
     */
    detailed?: object;
}

/**
 * Check if a given object implements the PluginsCatalogListPluginsResponse interface.
 */
export function instanceOfPluginsCatalogListPluginsResponse(value: object): value is PluginsCatalogListPluginsResponse {
    return true;
}

export function PluginsCatalogListPluginsResponseFromJSON(json: any): PluginsCatalogListPluginsResponse {
    return PluginsCatalogListPluginsResponseFromJSONTyped(json, false);
}

export function PluginsCatalogListPluginsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginsCatalogListPluginsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'detailed': json['detailed'] == null ? undefined : json['detailed'],
    };
}

export function PluginsCatalogListPluginsResponseToJSON(json: any): PluginsCatalogListPluginsResponse {
    return PluginsCatalogListPluginsResponseToJSONTyped(json, false);
}

export function PluginsCatalogListPluginsResponseToJSONTyped(value?: PluginsCatalogListPluginsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detailed': value['detailed'],
    };
}

