/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemWriteReplicationDrSecondaryDisableRequest
 */
export interface SystemWriteReplicationDrSecondaryDisableRequest {
    /**
     * DR operation token used to authorize this request.
     * @type {string}
     * @memberof SystemWriteReplicationDrSecondaryDisableRequest
     */
    drOperationToken?: string;
}

/**
 * Check if a given object implements the SystemWriteReplicationDrSecondaryDisableRequest interface.
 */
export function instanceOfSystemWriteReplicationDrSecondaryDisableRequest(value: object): value is SystemWriteReplicationDrSecondaryDisableRequest {
    return true;
}

export function SystemWriteReplicationDrSecondaryDisableRequestFromJSON(json: any): SystemWriteReplicationDrSecondaryDisableRequest {
    return SystemWriteReplicationDrSecondaryDisableRequestFromJSONTyped(json, false);
}

export function SystemWriteReplicationDrSecondaryDisableRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemWriteReplicationDrSecondaryDisableRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'drOperationToken': json['dr_operation_token'] == null ? undefined : json['dr_operation_token'],
    };
}

export function SystemWriteReplicationDrSecondaryDisableRequestToJSON(json: any): SystemWriteReplicationDrSecondaryDisableRequest {
    return SystemWriteReplicationDrSecondaryDisableRequestToJSONTyped(json, false);
}

export function SystemWriteReplicationDrSecondaryDisableRequestToJSONTyped(value?: SystemWriteReplicationDrSecondaryDisableRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dr_operation_token': value['drOperationToken'],
    };
}

