/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemPatchNamespacesPathRequest
 */
export interface SystemPatchNamespacesPathRequest {
    /**
     * User-provided key-value pairs that are used to describe arbitrary information about a namespace.
     * @type {object}
     * @memberof SystemPatchNamespacesPathRequest
     */
    customMetadata?: object;
}

/**
 * Check if a given object implements the SystemPatchNamespacesPathRequest interface.
 */
export function instanceOfSystemPatchNamespacesPathRequest(value: object): value is SystemPatchNamespacesPathRequest {
    return true;
}

export function SystemPatchNamespacesPathRequestFromJSON(json: any): SystemPatchNamespacesPathRequest {
    return SystemPatchNamespacesPathRequestFromJSONTyped(json, false);
}

export function SystemPatchNamespacesPathRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemPatchNamespacesPathRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customMetadata': json['custom_metadata'] == null ? undefined : json['custom_metadata'],
    };
}

export function SystemPatchNamespacesPathRequestToJSON(json: any): SystemPatchNamespacesPathRequest {
    return SystemPatchNamespacesPathRequestToJSONTyped(json, false);
}

export function SystemPatchNamespacesPathRequestToJSONTyped(value?: SystemPatchNamespacesPathRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'custom_metadata': value['customMetadata'],
    };
}

