/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemWriteSyncDestinationsVercelProjectNameResponse
 */
export interface SystemWriteSyncDestinationsVercelProjectNameResponse {
    /**
     * List of key value pairs of information necessary to connect with the external system.
     * @type {object}
     * @memberof SystemWriteSyncDestinationsVercelProjectNameResponse
     */
    connectionDetails?: object;
    /**
     * Name of this secrets store.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsVercelProjectNameResponse
     */
    name?: string;
    /**
     * Type of this secrets store.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsVercelProjectNameResponse
     */
    type?: string;
}

/**
 * Check if a given object implements the SystemWriteSyncDestinationsVercelProjectNameResponse interface.
 */
export function instanceOfSystemWriteSyncDestinationsVercelProjectNameResponse(value: object): value is SystemWriteSyncDestinationsVercelProjectNameResponse {
    return true;
}

export function SystemWriteSyncDestinationsVercelProjectNameResponseFromJSON(json: any): SystemWriteSyncDestinationsVercelProjectNameResponse {
    return SystemWriteSyncDestinationsVercelProjectNameResponseFromJSONTyped(json, false);
}

export function SystemWriteSyncDestinationsVercelProjectNameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemWriteSyncDestinationsVercelProjectNameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionDetails': json['connection_details'] == null ? undefined : json['connection_details'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function SystemWriteSyncDestinationsVercelProjectNameResponseToJSON(json: any): SystemWriteSyncDestinationsVercelProjectNameResponse {
    return SystemWriteSyncDestinationsVercelProjectNameResponseToJSONTyped(json, false);
}

export function SystemWriteSyncDestinationsVercelProjectNameResponseToJSONTyped(value?: SystemWriteSyncDestinationsVercelProjectNameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection_details': value['connectionDetails'],
        'name': value['name'],
        'type': value['type'],
    };
}

