/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponse
 */
export interface SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponse {
    /**
     * Map of Vault secrets associated with a given external destination.
     * @type {object}
     * @memberof SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponse
     */
    associatedSecrets?: object;
}

/**
 * Check if a given object implements the SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponse interface.
 */
export function instanceOfSystemWriteSyncDestinationsTypeNameAssociationsRemoveResponse(value: object): value is SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponse {
    return true;
}

export function SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponseFromJSON(json: any): SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponse {
    return SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponseFromJSONTyped(json, false);
}

export function SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'associatedSecrets': json['associated_secrets'] == null ? undefined : json['associated_secrets'],
    };
}

export function SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponseToJSON(json: any): SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponse {
    return SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponseToJSONTyped(json, false);
}

export function SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponseToJSONTyped(value?: SystemWriteSyncDestinationsTypeNameAssociationsRemoveResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'associated_secrets': value['associatedSecrets'],
    };
}

