/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemWriteSyncDestinationsGhNameResponse
 */
export interface SystemWriteSyncDestinationsGhNameResponse {
    /**
     * List of key value pairs of information necessary to connect with the external system.
     * @type {object}
     * @memberof SystemWriteSyncDestinationsGhNameResponse
     */
    connectionDetails?: object;
    /**
     * Name of this secrets store.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsGhNameResponse
     */
    name?: string;
    /**
     * List of key value pairs of Vault configuration options.
     * @type {object}
     * @memberof SystemWriteSyncDestinationsGhNameResponse
     */
    options?: object;
    /**
     * Error message if the purge job failed.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsGhNameResponse
     */
    purgeError?: string;
    /**
     * Timestamp of when a purge job was initiated when deleting a destination.
     * @type {Date}
     * @memberof SystemWriteSyncDestinationsGhNameResponse
     */
    purgeInitiatedAt?: Date;
    /**
     * Type of this secrets store.
     * @type {string}
     * @memberof SystemWriteSyncDestinationsGhNameResponse
     */
    type?: string;
}

/**
 * Check if a given object implements the SystemWriteSyncDestinationsGhNameResponse interface.
 */
export function instanceOfSystemWriteSyncDestinationsGhNameResponse(value: object): value is SystemWriteSyncDestinationsGhNameResponse {
    return true;
}

export function SystemWriteSyncDestinationsGhNameResponseFromJSON(json: any): SystemWriteSyncDestinationsGhNameResponse {
    return SystemWriteSyncDestinationsGhNameResponseFromJSONTyped(json, false);
}

export function SystemWriteSyncDestinationsGhNameResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemWriteSyncDestinationsGhNameResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'connectionDetails': json['connection_details'] == null ? undefined : json['connection_details'],
        'name': json['name'] == null ? undefined : json['name'],
        'options': json['options'] == null ? undefined : json['options'],
        'purgeError': json['purge_error'] == null ? undefined : json['purge_error'],
        'purgeInitiatedAt': json['purge_initiated_at'] == null ? undefined : (new Date(json['purge_initiated_at'])),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function SystemWriteSyncDestinationsGhNameResponseToJSON(json: any): SystemWriteSyncDestinationsGhNameResponse {
    return SystemWriteSyncDestinationsGhNameResponseToJSONTyped(json, false);
}

export function SystemWriteSyncDestinationsGhNameResponseToJSONTyped(value?: SystemWriteSyncDestinationsGhNameResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connection_details': value['connectionDetails'],
        'name': value['name'],
        'options': value['options'],
        'purge_error': value['purgeError'],
        'purge_initiated_at': value['purgeInitiatedAt'] == null ? undefined : ((value['purgeInitiatedAt']).toISOString()),
        'type': value['type'],
    };
}

