/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransitGenerateHmacWithAlgorithmRequest
 */
export interface TransitGenerateHmacWithAlgorithmRequest {
    /**
     * Algorithm to use (POST body parameter). Valid values are: * sha2-224 * sha2-256 * sha2-384 * sha2-512 * sha3-224 * sha3-256 * sha3-384 * sha3-512 Defaults to "sha2-256".
     * @type {string}
     * @memberof TransitGenerateHmacWithAlgorithmRequest
     */
    algorithm?: string;
    /**
     * Specifies a list of items to be processed in a single batch. When this parameter is set, if the parameter 'input' is also set, it will be ignored. Any batch output will preserve the order of the batch input.
     * @type {Array<object>}
     * @memberof TransitGenerateHmacWithAlgorithmRequest
     */
    batchInput?: Array<object>;
    /**
     * The base64-encoded input data
     * @type {string}
     * @memberof TransitGenerateHmacWithAlgorithmRequest
     */
    input?: string;
    /**
     * The version of the key to use for generating the HMAC. Must be 0 (for latest) or a value greater than or equal to the min_encryption_version configured on the key.
     * @type {number}
     * @memberof TransitGenerateHmacWithAlgorithmRequest
     */
    keyVersion?: number;
}

/**
 * Check if a given object implements the TransitGenerateHmacWithAlgorithmRequest interface.
 */
export function instanceOfTransitGenerateHmacWithAlgorithmRequest(value: object): value is TransitGenerateHmacWithAlgorithmRequest {
    return true;
}

export function TransitGenerateHmacWithAlgorithmRequestFromJSON(json: any): TransitGenerateHmacWithAlgorithmRequest {
    return TransitGenerateHmacWithAlgorithmRequestFromJSONTyped(json, false);
}

export function TransitGenerateHmacWithAlgorithmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransitGenerateHmacWithAlgorithmRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'algorithm': json['algorithm'] == null ? undefined : json['algorithm'],
        'batchInput': json['batch_input'] == null ? undefined : json['batch_input'],
        'input': json['input'] == null ? undefined : json['input'],
        'keyVersion': json['key_version'] == null ? undefined : json['key_version'],
    };
}

export function TransitGenerateHmacWithAlgorithmRequestToJSON(json: any): TransitGenerateHmacWithAlgorithmRequest {
    return TransitGenerateHmacWithAlgorithmRequestToJSONTyped(json, false);
}

export function TransitGenerateHmacWithAlgorithmRequestToJSONTyped(value?: TransitGenerateHmacWithAlgorithmRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'algorithm': value['algorithm'],
        'batch_input': value['batchInput'],
        'input': value['input'],
        'key_version': value['keyVersion'],
    };
}

