/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransitHashRequest
 */
export interface TransitHashRequest {
    /**
     * Algorithm to use (POST body parameter). Valid values are: * sha2-224 * sha2-256 * sha2-384 * sha2-512 * sha3-224 * sha3-256 * sha3-384 * sha3-512 Defaults to "sha2-256".
     * @type {string}
     * @memberof TransitHashRequest
     */
    algorithm?: string;
    /**
     * Encoding format to use. Can be "hex" or "base64". Defaults to "hex".
     * @type {string}
     * @memberof TransitHashRequest
     */
    format?: string;
    /**
     * The base64-encoded input data
     * @type {string}
     * @memberof TransitHashRequest
     */
    input?: string;
}

/**
 * Check if a given object implements the TransitHashRequest interface.
 */
export function instanceOfTransitHashRequest(value: object): value is TransitHashRequest {
    return true;
}

export function TransitHashRequestFromJSON(json: any): TransitHashRequest {
    return TransitHashRequestFromJSONTyped(json, false);
}

export function TransitHashRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransitHashRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'algorithm': json['algorithm'] == null ? undefined : json['algorithm'],
        'format': json['format'] == null ? undefined : json['format'],
        'input': json['input'] == null ? undefined : json['input'],
    };
}

export function TransitHashRequestToJSON(json: any): TransitHashRequest {
    return TransitHashRequestToJSONTyped(json, false);
}

export function TransitHashRequestToJSONTyped(value?: TransitHashRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'algorithm': value['algorithm'],
        'format': value['format'],
        'input': value['input'],
    };
}

