/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UiConfigReadCustomMessageResponse
 */
export interface UiConfigReadCustomMessageResponse {
    /**
     * 
     * @type {string}
     * @memberof UiConfigReadCustomMessageResponse
     */
    id?: string;
}

/**
 * Check if a given object implements the UiConfigReadCustomMessageResponse interface.
 */
export function instanceOfUiConfigReadCustomMessageResponse(value: object): value is UiConfigReadCustomMessageResponse {
    return true;
}

export function UiConfigReadCustomMessageResponseFromJSON(json: any): UiConfigReadCustomMessageResponse {
    return UiConfigReadCustomMessageResponseFromJSONTyped(json, false);
}

export function UiConfigReadCustomMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UiConfigReadCustomMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function UiConfigReadCustomMessageResponseToJSON(json: any): UiConfigReadCustomMessageResponse {
    return UiConfigReadCustomMessageResponseToJSONTyped(json, false);
}

export function UiConfigReadCustomMessageResponseToJSONTyped(value?: UiConfigReadCustomMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

