/* tslint:disable */
/* eslint-disable */
/**
 * HashiCorp Vault API
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.21.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UiLoginDefaultAuthListResponse
 */
export interface UiLoginDefaultAuthListResponse {
    /**
     * 
     * @type {object}
     * @memberof UiLoginDefaultAuthListResponse
     */
    keyInfo?: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof UiLoginDefaultAuthListResponse
     */
    keys?: Array<string>;
}

/**
 * Check if a given object implements the UiLoginDefaultAuthListResponse interface.
 */
export function instanceOfUiLoginDefaultAuthListResponse(value: object): value is UiLoginDefaultAuthListResponse {
    return true;
}

export function UiLoginDefaultAuthListResponseFromJSON(json: any): UiLoginDefaultAuthListResponse {
    return UiLoginDefaultAuthListResponseFromJSONTyped(json, false);
}

export function UiLoginDefaultAuthListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UiLoginDefaultAuthListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'keyInfo': json['key_info'] == null ? undefined : json['key_info'],
        'keys': json['keys'] == null ? undefined : json['keys'],
    };
}

export function UiLoginDefaultAuthListResponseToJSON(json: any): UiLoginDefaultAuthListResponse {
    return UiLoginDefaultAuthListResponseToJSONTyped(json, false);
}

export function UiLoginDefaultAuthListResponseToJSONTyped(value?: UiLoginDefaultAuthListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key_info': value['keyInfo'],
        'keys': value['keys'],
    };
}

