# ***
# WARNING: Do not EDIT or MERGE this file, it is generated by packagespec.
# ***

LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ID             := 00-base-c6cdf1b224722d2520e082320f2a71875913247c
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_TYPE           := base
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_BASE_LAYER     := 
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_INCLUDE := 
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_EXCLUDE := 
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_CACHE_KEY_FILE := .buildcache/cache-keys/base-c6cdf1b224722d2520e082320f2a71875913247c
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ARCHIVE_FILE   := .buildcache/archives/00-base-c6cdf1b224722d2520e082320f2a71875913247c.tar.gz
$(eval $(call LAYER,$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ID),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_TYPE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_BASE_LAYER),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_INCLUDE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_EXCLUDE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_CACHE_KEY_FILE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ARCHIVE_FILE)))

LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_ID             := 01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a
LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_TYPE           := install-go
LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_BASE_LAYER     := 00-base-c6cdf1b224722d2520e082320f2a71875913247c
LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_SOURCE_INCLUDE := 
LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_SOURCE_EXCLUDE := 
LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_CACHE_KEY_FILE := .buildcache/cache-keys/install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a
LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_ARCHIVE_FILE   := .buildcache/archives/01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a.tar.gz
$(eval $(call LAYER,$(LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_ID),$(LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_TYPE),$(LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_BASE_LAYER),$(LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_SOURCE_INCLUDE),$(LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_SOURCE_EXCLUDE),$(LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_CACHE_KEY_FILE),$(LAYER_01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a_ARCHIVE_FILE)))

LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_ID             := 02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967
LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_TYPE           := install-go-tools
LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_BASE_LAYER     := 01-install-go-3e1bde065b1b93415ed248fa3d5c1c05cc69584a
LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_SOURCE_INCLUDE := 
LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_SOURCE_EXCLUDE := 
LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_CACHE_KEY_FILE := .buildcache/cache-keys/install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967
LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_ARCHIVE_FILE   := .buildcache/archives/02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967.tar.gz
$(eval $(call LAYER,$(LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_ID),$(LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_TYPE),$(LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_BASE_LAYER),$(LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_SOURCE_INCLUDE),$(LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_SOURCE_EXCLUDE),$(LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_CACHE_KEY_FILE),$(LAYER_02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967_ARCHIVE_FILE)))

LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_ID             := 03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf
LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_TYPE           := set-workdir
LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_BASE_LAYER     := 02-install-go-tools-812d96adc90c57c2b108e6f2d3a0e559c52cb967
LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_SOURCE_INCLUDE := 
LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_SOURCE_EXCLUDE := 
LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_CACHE_KEY_FILE := .buildcache/cache-keys/set-workdir-211877846cfaed52439943f37a49b817ae0fceaf
LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_ARCHIVE_FILE   := .buildcache/archives/03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf.tar.gz
$(eval $(call LAYER,$(LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_ID),$(LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_TYPE),$(LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_BASE_LAYER),$(LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_SOURCE_INCLUDE),$(LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_SOURCE_EXCLUDE),$(LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_CACHE_KEY_FILE),$(LAYER_03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf_ARCHIVE_FILE)))

LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_ID             := 04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd
LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_TYPE           := install-yarn
LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_BASE_LAYER     := 03-set-workdir-211877846cfaed52439943f37a49b817ae0fceaf
LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_SOURCE_INCLUDE := 
LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_SOURCE_EXCLUDE := 
LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_CACHE_KEY_FILE := .buildcache/cache-keys/install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd
LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_ARCHIVE_FILE   := .buildcache/archives/04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd.tar.gz
$(eval $(call LAYER,$(LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_ID),$(LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_TYPE),$(LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_BASE_LAYER),$(LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_SOURCE_INCLUDE),$(LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_SOURCE_EXCLUDE),$(LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_CACHE_KEY_FILE),$(LAYER_04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd_ARCHIVE_FILE)))

LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_ID             := 05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3
LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_TYPE           := ui-dependencies
LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_BASE_LAYER     := 04-install-yarn-4aec70f4651142abeec09a468d907c30ddf46fbd
LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_SOURCE_INCLUDE := ui/package.json ui/yarn.lock
LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_SOURCE_EXCLUDE := 
LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_CACHE_KEY_FILE := .buildcache/cache-keys/ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3
LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_ARCHIVE_FILE   := .buildcache/archives/05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3.tar.gz
$(eval $(call LAYER,$(LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_ID),$(LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_TYPE),$(LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_BASE_LAYER),$(LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_SOURCE_INCLUDE),$(LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_SOURCE_EXCLUDE),$(LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_CACHE_KEY_FILE),$(LAYER_05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3_ARCHIVE_FILE)))

LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_ID             := 06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2
LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_TYPE           := build-ui
LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_BASE_LAYER     := 05-ui-dependencies-0fdbdc16f9e94141040a827d03ca653a60ca7ae3
LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_SOURCE_INCLUDE := ui/
LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_SOURCE_EXCLUDE := 
LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_CACHE_KEY_FILE := .buildcache/cache-keys/build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2
LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_ARCHIVE_FILE   := .buildcache/archives/06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2.tar.gz
$(eval $(call LAYER,$(LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_ID),$(LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_TYPE),$(LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_BASE_LAYER),$(LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_SOURCE_INCLUDE),$(LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_SOURCE_EXCLUDE),$(LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_CACHE_KEY_FILE),$(LAYER_06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2_ARCHIVE_FILE)))

LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_ID             := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_TYPE           := build-static-assets
LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_BASE_LAYER     := 06-build-ui-25272f1b9d9569e0b0fd4fe503bc4f4cfb1a59d2
LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_SOURCE_INCLUDE := Makefile
LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_SOURCE_EXCLUDE := 
LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_CACHE_KEY_FILE := .buildcache/cache-keys/build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_ARCHIVE_FILE   := .buildcache/archives/07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443.tar.gz
$(eval $(call LAYER,$(LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_ID),$(LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_TYPE),$(LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_BASE_LAYER),$(LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_SOURCE_INCLUDE),$(LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_SOURCE_EXCLUDE),$(LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_CACHE_KEY_FILE),$(LAYER_07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_ID             := 08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9
LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9
LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_ID),$(LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_TYPE),$(LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_ID             := 08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c
LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c
LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_ID),$(LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_TYPE),$(LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_ID             := 08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55
LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55
LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_ID),$(LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_TYPE),$(LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_ID             := 08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482
LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482
LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_ID),$(LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_TYPE),$(LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_ID             := 08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9
LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9
LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_ID),$(LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_TYPE),$(LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_ID             := 08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e
LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e
LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_ID),$(LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_TYPE),$(LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_ID             := 08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782
LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782
LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_ID),$(LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_TYPE),$(LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_ID             := 08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad
LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad
LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_ID),$(LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_TYPE),$(LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_ID             := 08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6
LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6
LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_ID),$(LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_TYPE),$(LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_ID             := 08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e
LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e
LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_ID),$(LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_TYPE),$(LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_ID             := 08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8
LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8
LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_ID),$(LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_TYPE),$(LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_ID             := 08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459
LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459
LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_ID),$(LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_TYPE),$(LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_ID             := 08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41
LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41
LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_ID),$(LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_TYPE),$(LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_ID             := 08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652
LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652
LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_ID),$(LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_TYPE),$(LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_ID             := 08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7
LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7
LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_ID),$(LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_TYPE),$(LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_ID             := 08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf
LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_BASE_LAYER     := 07-build-static-assets-aa026166dcc5a4273c7003aae00ec9040e84c443
LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf
LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_ID),$(LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_TYPE),$(LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf_ARCHIVE_FILE)))

LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_ID             := 09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a
LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_TYPE           := copy-source
LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_BASE_LAYER     := 08-warm-go-build-vendor-cache-033f943a1550769094587a14ca2adfa36ff51ce9
LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_SOURCE_INCLUDE := .
LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a
LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_ID),$(LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_TYPE),$(LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_BASE_LAYER),$(LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_SOURCE_INCLUDE),$(LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_SOURCE_EXCLUDE),$(LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_CACHE_KEY_FILE),$(LAYER_09-copy-source-0364c438a2733f1e873e9bbe964d360823c9cc5a_ARCHIVE_FILE)))

LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_ID             := 09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e
LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_TYPE           := copy-source
LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_BASE_LAYER     := 08-warm-go-build-vendor-cache-e79f9f58a01b3b27b4e82f65bb1f4da1b751e652
LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_SOURCE_INCLUDE := .
LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e
LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_ID),$(LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_TYPE),$(LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_BASE_LAYER),$(LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_SOURCE_INCLUDE),$(LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_SOURCE_EXCLUDE),$(LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_CACHE_KEY_FILE),$(LAYER_09-copy-source-420abe8cbf7f8effcabf00cbcf3bb301c6a9225e_ARCHIVE_FILE)))

LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_ID             := 09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a
LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_TYPE           := copy-source
LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_BASE_LAYER     := 08-warm-go-build-vendor-cache-da79461d6faaf532e207aea109c094e9b79f5a41
LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_SOURCE_INCLUDE := .
LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a
LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_ID),$(LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_TYPE),$(LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_BASE_LAYER),$(LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_SOURCE_INCLUDE),$(LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_SOURCE_EXCLUDE),$(LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_CACHE_KEY_FILE),$(LAYER_09-copy-source-4e0b8d35741ebeb426fbde9b36d955a42af5988a_ARCHIVE_FILE)))

LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_ID             := 09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f
LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_TYPE           := copy-source
LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_BASE_LAYER     := 08-warm-go-build-vendor-cache-5bee5d7107db0c8f009383bc6bf7388906e3d782
LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_SOURCE_INCLUDE := .
LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f
LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_ID),$(LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_TYPE),$(LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_BASE_LAYER),$(LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_SOURCE_INCLUDE),$(LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_SOURCE_EXCLUDE),$(LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_CACHE_KEY_FILE),$(LAYER_09-copy-source-5b6c4ca4c7835ff7fb51c712347ec3319a2ec77f_ARCHIVE_FILE)))

LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_ID             := 09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b
LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_TYPE           := copy-source
LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_BASE_LAYER     := 08-warm-go-build-vendor-cache-f3090a3f50d02c0766397913c2fc5e0a2d79a7cf
LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_SOURCE_INCLUDE := .
LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b
LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_ID),$(LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_TYPE),$(LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_BASE_LAYER),$(LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_SOURCE_INCLUDE),$(LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_SOURCE_EXCLUDE),$(LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_CACHE_KEY_FILE),$(LAYER_09-copy-source-785853119fd3fa8bf88fc76dd18d358ee1db7b4b_ARCHIVE_FILE)))

LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_ID             := 09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b
LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_TYPE           := copy-source
LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_BASE_LAYER     := 08-warm-go-build-vendor-cache-47e6eee8c81c4076f45112e15335333bf3d0b56e
LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_SOURCE_INCLUDE := .
LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b
LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_ID),$(LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_TYPE),$(LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_BASE_LAYER),$(LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_SOURCE_INCLUDE),$(LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_SOURCE_EXCLUDE),$(LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_CACHE_KEY_FILE),$(LAYER_09-copy-source-7acf7b1a058045bcd55c30ed2c8bda40c3cdac5b_ARCHIVE_FILE)))

LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_ID             := 09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3
LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_TYPE           := copy-source
LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_BASE_LAYER     := 08-warm-go-build-vendor-cache-b475067be90a555f4e3882636b9668f6b9b4d459
LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_SOURCE_INCLUDE := .
LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3
LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_ID),$(LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_TYPE),$(LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_BASE_LAYER),$(LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_SOURCE_INCLUDE),$(LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_SOURCE_EXCLUDE),$(LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_CACHE_KEY_FILE),$(LAYER_09-copy-source-8707e86a67b8413353e26b832fab4ae65cedefe3_ARCHIVE_FILE)))

LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_ID             := 09-copy-source-ae22226bd23985e9182fb643e991b98260317d46
LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_TYPE           := copy-source
LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_BASE_LAYER     := 08-warm-go-build-vendor-cache-712ec7cde537a32bef2432475a331d468fc586ad
LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_SOURCE_INCLUDE := .
LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-ae22226bd23985e9182fb643e991b98260317d46
LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-ae22226bd23985e9182fb643e991b98260317d46.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_ID),$(LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_TYPE),$(LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_BASE_LAYER),$(LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_SOURCE_INCLUDE),$(LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_SOURCE_EXCLUDE),$(LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_CACHE_KEY_FILE),$(LAYER_09-copy-source-ae22226bd23985e9182fb643e991b98260317d46_ARCHIVE_FILE)))

LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_ID             := 09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df
LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_TYPE           := copy-source
LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_BASE_LAYER     := 08-warm-go-build-vendor-cache-8d1d35962329f894b69eae2597bb2d061fafdd0e
LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_SOURCE_INCLUDE := .
LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df
LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_ID),$(LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_TYPE),$(LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_BASE_LAYER),$(LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_SOURCE_INCLUDE),$(LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_SOURCE_EXCLUDE),$(LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_CACHE_KEY_FILE),$(LAYER_09-copy-source-ba7fcd8785f3269b511385a81e50f0ff7913a2df_ARCHIVE_FILE)))

LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_ID             := 09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9
LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_TYPE           := copy-source
LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_BASE_LAYER     := 08-warm-go-build-vendor-cache-eeecfd516736e1df88c64e819702f7f74dc288d7
LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_SOURCE_INCLUDE := .
LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-c38080546e013388629a5c136f7d05584eb7c0b9
LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_ID),$(LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_TYPE),$(LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_BASE_LAYER),$(LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_SOURCE_INCLUDE),$(LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_SOURCE_EXCLUDE),$(LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_CACHE_KEY_FILE),$(LAYER_09-copy-source-c38080546e013388629a5c136f7d05584eb7c0b9_ARCHIVE_FILE)))

LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_ID             := 09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04
LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_TYPE           := copy-source
LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_BASE_LAYER     := 08-warm-go-build-vendor-cache-44ded9c13dd86aab6b169ab17c1dca800cb245d9
LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_SOURCE_INCLUDE := .
LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-c60c16e8804497c665759efaf3e94207970b3d04
LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_ID),$(LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_TYPE),$(LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_BASE_LAYER),$(LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_SOURCE_INCLUDE),$(LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_SOURCE_EXCLUDE),$(LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_CACHE_KEY_FILE),$(LAYER_09-copy-source-c60c16e8804497c665759efaf3e94207970b3d04_ARCHIVE_FILE)))

LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_ID             := 09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac
LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_TYPE           := copy-source
LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_BASE_LAYER     := 08-warm-go-build-vendor-cache-7262cee5d8bc455704c4562c7532ccb42d9680c6
LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_SOURCE_INCLUDE := .
LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac
LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_ID),$(LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_TYPE),$(LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_BASE_LAYER),$(LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_SOURCE_INCLUDE),$(LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_SOURCE_EXCLUDE),$(LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_CACHE_KEY_FILE),$(LAYER_09-copy-source-ddf58f0e427c533bce78aec8ad34a621183a5eac_ARCHIVE_FILE)))

LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_ID             := 09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9
LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_TYPE           := copy-source
LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_BASE_LAYER     := 08-warm-go-build-vendor-cache-aefbd1864003507ee009279de366510792b4c3f8
LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_SOURCE_INCLUDE := .
LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9
LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_ID),$(LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_TYPE),$(LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_BASE_LAYER),$(LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_SOURCE_INCLUDE),$(LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_SOURCE_EXCLUDE),$(LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_CACHE_KEY_FILE),$(LAYER_09-copy-source-ece0007981a88403bceaa9334a31d1e56838e9f9_ARCHIVE_FILE)))

LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_ID             := 09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591
LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_TYPE           := copy-source
LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_BASE_LAYER     := 08-warm-go-build-vendor-cache-331aff34b7d8fa6cd582c859826ed14842ca7482
LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_SOURCE_INCLUDE := .
LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591
LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_ID),$(LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_TYPE),$(LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_BASE_LAYER),$(LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_SOURCE_INCLUDE),$(LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_SOURCE_EXCLUDE),$(LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_CACHE_KEY_FILE),$(LAYER_09-copy-source-ee0415391f77b74a70b18d8a7ff2bdc7e20c2591_ARCHIVE_FILE)))

LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_ID             := 09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9
LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_TYPE           := copy-source
LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_BASE_LAYER     := 08-warm-go-build-vendor-cache-10fa96a556c74dd621505ce8e264e0bc02cfe56c
LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_SOURCE_INCLUDE := .
LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9
LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_ID),$(LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_TYPE),$(LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_BASE_LAYER),$(LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_SOURCE_INCLUDE),$(LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_SOURCE_EXCLUDE),$(LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_CACHE_KEY_FILE),$(LAYER_09-copy-source-fcdb3829e97b4b4ce227b2878afcad50a5d365a9_ARCHIVE_FILE)))

LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_ID             := 09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb
LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_TYPE           := copy-source
LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_BASE_LAYER     := 08-warm-go-build-vendor-cache-1e6f9bac3b619d96c05b2085920060e7637a3b55
LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_SOURCE_INCLUDE := .
LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb
LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_ID),$(LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_TYPE),$(LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_BASE_LAYER),$(LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_SOURCE_INCLUDE),$(LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_SOURCE_EXCLUDE),$(LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_CACHE_KEY_FILE),$(LAYER_09-copy-source-fee3e9ae293481da1c20ce97546b3b8751d636fb_ARCHIVE_FILE)))
