# ***
# WARNING: Do not EDIT or MERGE this file, it is generated by packagespec.
# ***

LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ID             := 00-base-c6cdf1b224722d2520e082320f2a71875913247c
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_TYPE           := base
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_BASE_LAYER     := 
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_INCLUDE := 
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_EXCLUDE := 
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_CACHE_KEY_FILE := .buildcache/cache-keys/base-c6cdf1b224722d2520e082320f2a71875913247c
LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ARCHIVE_FILE   := .buildcache/archives/00-base-c6cdf1b224722d2520e082320f2a71875913247c.tar.gz
$(eval $(call LAYER,$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ID),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_TYPE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_BASE_LAYER),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_INCLUDE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_SOURCE_EXCLUDE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_CACHE_KEY_FILE),$(LAYER_00-base-c6cdf1b224722d2520e082320f2a71875913247c_ARCHIVE_FILE)))

LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_ID             := 01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_TYPE           := install-go
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_BASE_LAYER     := 00-base-c6cdf1b224722d2520e082320f2a71875913247c
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_SOURCE_INCLUDE := 
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_SOURCE_EXCLUDE := 
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_CACHE_KEY_FILE := .buildcache/cache-keys/install-go-f39f5d66161bdd79b182943a3accdd95510c4812
LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_ARCHIVE_FILE   := .buildcache/archives/01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812.tar.gz
$(eval $(call LAYER,$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_ID),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_TYPE),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_BASE_LAYER),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_SOURCE_INCLUDE),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_SOURCE_EXCLUDE),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_CACHE_KEY_FILE),$(LAYER_01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812_ARCHIVE_FILE)))

LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_ID             := 02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837
LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_TYPE           := install-go-tools
LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_BASE_LAYER     := 01-install-go-f39f5d66161bdd79b182943a3accdd95510c4812
LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_SOURCE_INCLUDE := 
LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_SOURCE_EXCLUDE := 
LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_CACHE_KEY_FILE := .buildcache/cache-keys/install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837
LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_ARCHIVE_FILE   := .buildcache/archives/02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837.tar.gz
$(eval $(call LAYER,$(LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_ID),$(LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_TYPE),$(LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_BASE_LAYER),$(LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_SOURCE_INCLUDE),$(LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_SOURCE_EXCLUDE),$(LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_CACHE_KEY_FILE),$(LAYER_02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837_ARCHIVE_FILE)))

LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_ID             := 03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112
LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_TYPE           := set-workdir
LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_BASE_LAYER     := 02-install-go-tools-f4bc704e2a2b6b361aafa571dc84bbfd63acb837
LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_SOURCE_INCLUDE := 
LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_SOURCE_EXCLUDE := 
LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_CACHE_KEY_FILE := .buildcache/cache-keys/set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112
LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_ARCHIVE_FILE   := .buildcache/archives/03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112.tar.gz
$(eval $(call LAYER,$(LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_ID),$(LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_TYPE),$(LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_BASE_LAYER),$(LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_SOURCE_INCLUDE),$(LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_SOURCE_EXCLUDE),$(LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_CACHE_KEY_FILE),$(LAYER_03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112_ARCHIVE_FILE)))

LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_ID             := 04-install-yarn-ead118201fef771b223684be1b11a96eb244d172
LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_TYPE           := install-yarn
LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_BASE_LAYER     := 03-set-workdir-59a56855adfc3babdb315e81dfd4acae482b7112
LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_SOURCE_INCLUDE := 
LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_SOURCE_EXCLUDE := 
LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_CACHE_KEY_FILE := .buildcache/cache-keys/install-yarn-ead118201fef771b223684be1b11a96eb244d172
LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_ARCHIVE_FILE   := .buildcache/archives/04-install-yarn-ead118201fef771b223684be1b11a96eb244d172.tar.gz
$(eval $(call LAYER,$(LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_ID),$(LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_TYPE),$(LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_BASE_LAYER),$(LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_SOURCE_INCLUDE),$(LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_SOURCE_EXCLUDE),$(LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_CACHE_KEY_FILE),$(LAYER_04-install-yarn-ead118201fef771b223684be1b11a96eb244d172_ARCHIVE_FILE)))

LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_ID             := 05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb
LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_TYPE           := make-ui-folder
LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_BASE_LAYER     := 04-install-yarn-ead118201fef771b223684be1b11a96eb244d172
LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_SOURCE_INCLUDE := 
LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_SOURCE_EXCLUDE := 
LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_CACHE_KEY_FILE := .buildcache/cache-keys/make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb
LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_ARCHIVE_FILE   := .buildcache/archives/05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb.tar.gz
$(eval $(call LAYER,$(LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_ID),$(LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_TYPE),$(LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_BASE_LAYER),$(LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_SOURCE_INCLUDE),$(LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_SOURCE_EXCLUDE),$(LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_CACHE_KEY_FILE),$(LAYER_05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb_ARCHIVE_FILE)))

LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_ID             := 06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4
LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_TYPE           := ui-dependencies
LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_BASE_LAYER     := 05-make-ui-folder-bce980c9e67e07303e0196494902d65cbbe3f1fb
LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_SOURCE_INCLUDE := ui/package.json ui/yarn.lock
LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_SOURCE_EXCLUDE := 
LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_CACHE_KEY_FILE := .buildcache/cache-keys/ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4
LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_ARCHIVE_FILE   := .buildcache/archives/06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4.tar.gz
$(eval $(call LAYER,$(LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_ID),$(LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_TYPE),$(LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_BASE_LAYER),$(LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_SOURCE_INCLUDE),$(LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_SOURCE_EXCLUDE),$(LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_CACHE_KEY_FILE),$(LAYER_06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4_ARCHIVE_FILE)))

LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_ID             := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_TYPE           := build-ui
LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_BASE_LAYER     := 06-ui-dependencies-46d9ddc9b8b4f8e01ce998e608c6b25ef4a8d4f4
LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_SOURCE_INCLUDE := ui/
LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_SOURCE_EXCLUDE := 
LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_CACHE_KEY_FILE := .buildcache/cache-keys/build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_ARCHIVE_FILE   := .buildcache/archives/07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8.tar.gz
$(eval $(call LAYER,$(LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_ID),$(LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_TYPE),$(LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_BASE_LAYER),$(LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_SOURCE_INCLUDE),$(LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_SOURCE_EXCLUDE),$(LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_CACHE_KEY_FILE),$(LAYER_07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_ID             := 08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b
LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b
LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_ID),$(LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_TYPE),$(LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_ID             := 08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad
LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad
LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_ID),$(LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_TYPE),$(LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_ID             := 08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85
LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85
LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_ID),$(LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_TYPE),$(LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_ID             := 08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0
LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0
LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_ID),$(LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_TYPE),$(LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_ID             := 08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864
LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864
LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_ID),$(LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_TYPE),$(LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_ID             := 08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867
LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867
LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_ID),$(LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_TYPE),$(LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_ID             := 08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7
LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7
LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_ID),$(LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_TYPE),$(LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_ID             := 08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4
LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4
LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_ID),$(LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_TYPE),$(LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_ID             := 08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a
LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a
LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_ID),$(LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_TYPE),$(LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_ID             := 08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0
LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0
LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_ID),$(LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_TYPE),$(LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_ID             := 08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6
LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6
LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_ID),$(LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_TYPE),$(LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_ID             := 08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc
LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc
LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_ID),$(LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_TYPE),$(LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_ID             := 08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100
LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100
LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_ID),$(LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_TYPE),$(LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_ID             := 08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445
LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445
LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_ID),$(LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_TYPE),$(LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445_ARCHIVE_FILE)))

LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_ID             := 08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd
LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_TYPE           := warm-go-build-vendor-cache
LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_BASE_LAYER     := 07-build-ui-25c1068d5eb3c5d0171ed7c9ca3ee238a70196c8
LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_SOURCE_INCLUDE := vendor/
LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_SOURCE_EXCLUDE := 
LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_CACHE_KEY_FILE := .buildcache/cache-keys/warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd
LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_ARCHIVE_FILE   := .buildcache/archives/08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd.tar.gz
$(eval $(call LAYER,$(LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_ID),$(LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_TYPE),$(LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_BASE_LAYER),$(LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_SOURCE_INCLUDE),$(LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_SOURCE_EXCLUDE),$(LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_CACHE_KEY_FILE),$(LAYER_08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd_ARCHIVE_FILE)))

LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_ID             := 09-copy-source-03143140cf9fc032687936ad30751a6badfd7105
LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_TYPE           := copy-source
LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_BASE_LAYER     := 08-warm-go-build-vendor-cache-7b360b408559f47c0c64dcd31d2805040f33cae0
LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_SOURCE_INCLUDE := .
LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-03143140cf9fc032687936ad30751a6badfd7105
LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-03143140cf9fc032687936ad30751a6badfd7105.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_ID),$(LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_TYPE),$(LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_BASE_LAYER),$(LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_SOURCE_INCLUDE),$(LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_SOURCE_EXCLUDE),$(LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_CACHE_KEY_FILE),$(LAYER_09-copy-source-03143140cf9fc032687936ad30751a6badfd7105_ARCHIVE_FILE)))

LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_ID             := 09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80
LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_TYPE           := copy-source
LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_BASE_LAYER     := 08-warm-go-build-vendor-cache-3880d8fe97ad437f80b18bd422316c0592004867
LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_SOURCE_INCLUDE := .
LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-0324144f766e9b380cb3fa7cf357245815147e80
LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_ID),$(LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_TYPE),$(LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_BASE_LAYER),$(LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_SOURCE_INCLUDE),$(LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_SOURCE_EXCLUDE),$(LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_CACHE_KEY_FILE),$(LAYER_09-copy-source-0324144f766e9b380cb3fa7cf357245815147e80_ARCHIVE_FILE)))

LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_ID             := 09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650
LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_TYPE           := copy-source
LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_BASE_LAYER     := 08-warm-go-build-vendor-cache-4ee7db55b38ae991941d08ea19b17f1ce56417d4
LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_SOURCE_INCLUDE := .
LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-11b9c29608aedab79bfeae581aa3b511751cd650
LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_ID),$(LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_TYPE),$(LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_BASE_LAYER),$(LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_SOURCE_INCLUDE),$(LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_SOURCE_EXCLUDE),$(LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_CACHE_KEY_FILE),$(LAYER_09-copy-source-11b9c29608aedab79bfeae581aa3b511751cd650_ARCHIVE_FILE)))

LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_ID             := 09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8
LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_TYPE           := copy-source
LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_BASE_LAYER     := 08-warm-go-build-vendor-cache-4c4e3c7f6037331f00c8ba91926e353dcb584fc7
LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_SOURCE_INCLUDE := .
LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8
LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_ID),$(LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_TYPE),$(LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_BASE_LAYER),$(LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_SOURCE_INCLUDE),$(LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_SOURCE_EXCLUDE),$(LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_CACHE_KEY_FILE),$(LAYER_09-copy-source-350e831d60feacc39887f3ec1b5a192e2e0547c8_ARCHIVE_FILE)))

LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_ID             := 09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717
LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_TYPE           := copy-source
LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_BASE_LAYER     := 08-warm-go-build-vendor-cache-eeedc480cae24da0babb43391c75ee1804f8d6cd
LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_SOURCE_INCLUDE := .
LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-56c0020a55e36f882c512c93119837ddbffa1717
LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_ID),$(LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_TYPE),$(LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_BASE_LAYER),$(LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_SOURCE_INCLUDE),$(LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_SOURCE_EXCLUDE),$(LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_CACHE_KEY_FILE),$(LAYER_09-copy-source-56c0020a55e36f882c512c93119837ddbffa1717_ARCHIVE_FILE)))

LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_ID             := 09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92
LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_TYPE           := copy-source
LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_BASE_LAYER     := 08-warm-go-build-vendor-cache-ae6287464a479a88d1f619cad1b89414e47a6445
LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_SOURCE_INCLUDE := .
LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92
LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_ID),$(LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_TYPE),$(LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_BASE_LAYER),$(LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_SOURCE_INCLUDE),$(LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_SOURCE_EXCLUDE),$(LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_CACHE_KEY_FILE),$(LAYER_09-copy-source-5e58e72067daca3bdc5f5e6ed9bacaa4a34aea92_ARCHIVE_FILE)))

LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_ID             := 09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f
LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_TYPE           := copy-source
LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_BASE_LAYER     := 08-warm-go-build-vendor-cache-7251a6cde572d3a9036046ee8852c78b033ea87a
LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_SOURCE_INCLUDE := .
LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f
LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_ID),$(LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_TYPE),$(LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_BASE_LAYER),$(LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_SOURCE_INCLUDE),$(LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_SOURCE_EXCLUDE),$(LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_CACHE_KEY_FILE),$(LAYER_09-copy-source-7033c59eed705519f592a12054f41d6c0ac1ec3f_ARCHIVE_FILE)))

LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_ID             := 09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db
LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_TYPE           := copy-source
LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_BASE_LAYER     := 08-warm-go-build-vendor-cache-187e8a256384324588185ad46bd9ddf9f20d0b85
LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_SOURCE_INCLUDE := .
LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db
LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_ID),$(LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_TYPE),$(LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_BASE_LAYER),$(LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_SOURCE_INCLUDE),$(LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_SOURCE_EXCLUDE),$(LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_CACHE_KEY_FILE),$(LAYER_09-copy-source-8679dc9eab11b20ad680b3ef4c4a914097a684db_ARCHIVE_FILE)))

LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_ID             := 09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2
LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_TYPE           := copy-source
LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_BASE_LAYER     := 08-warm-go-build-vendor-cache-13d94b7206be4a43beda51b875e53a2f67d39fad
LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_SOURCE_INCLUDE := .
LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2
LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_ID),$(LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_TYPE),$(LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_BASE_LAYER),$(LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_SOURCE_INCLUDE),$(LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_SOURCE_EXCLUDE),$(LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_CACHE_KEY_FILE),$(LAYER_09-copy-source-97dedbf20c8f409abef7d204a312641f1b8413b2_ARCHIVE_FILE)))

LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_ID             := 09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f
LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_TYPE           := copy-source
LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_BASE_LAYER     := 08-warm-go-build-vendor-cache-823d88e7c35b82f918b469e2d4987b383069cea6
LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_SOURCE_INCLUDE := .
LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f
LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_ID),$(LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_TYPE),$(LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_BASE_LAYER),$(LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_SOURCE_INCLUDE),$(LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_SOURCE_EXCLUDE),$(LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_CACHE_KEY_FILE),$(LAYER_09-copy-source-bee6db62251e3689b5f83a2206a3ce8835198e7f_ARCHIVE_FILE)))

LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_ID             := 09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7
LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_TYPE           := copy-source
LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_BASE_LAYER     := 08-warm-go-build-vendor-cache-01af2589d5e1e981b1e099036e2ccac4225a3d4b
LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_SOURCE_INCLUDE := .
LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-c37536707658258e17cbd5990f0b0e88124766e7
LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_ID),$(LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_TYPE),$(LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_BASE_LAYER),$(LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_SOURCE_INCLUDE),$(LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_SOURCE_EXCLUDE),$(LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_CACHE_KEY_FILE),$(LAYER_09-copy-source-c37536707658258e17cbd5990f0b0e88124766e7_ARCHIVE_FILE)))

LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_ID             := 09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e
LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_TYPE           := copy-source
LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_BASE_LAYER     := 08-warm-go-build-vendor-cache-3478c9637f3b68b9fd3affe26aed6303a1749864
LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_SOURCE_INCLUDE := .
LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e
LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_ID),$(LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_TYPE),$(LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_BASE_LAYER),$(LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_SOURCE_INCLUDE),$(LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_SOURCE_EXCLUDE),$(LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_CACHE_KEY_FILE),$(LAYER_09-copy-source-ced15b746ab209c6bfc7cb3c13045f0e23cfe92e_ARCHIVE_FILE)))

LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_ID             := 09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c
LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_TYPE           := copy-source
LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_BASE_LAYER     := 08-warm-go-build-vendor-cache-8571f875aa642c0db2e0aab1b2cdc7cec38f91bc
LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_SOURCE_INCLUDE := .
LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c
LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_ID),$(LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_TYPE),$(LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_BASE_LAYER),$(LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_SOURCE_INCLUDE),$(LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_SOURCE_EXCLUDE),$(LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_CACHE_KEY_FILE),$(LAYER_09-copy-source-d3b493dc7d4c2eb8ebcd6090c4f6386a08ee884c_ARCHIVE_FILE)))

LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_ID             := 09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8
LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_TYPE           := copy-source
LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_BASE_LAYER     := 08-warm-go-build-vendor-cache-8aa2cb1e074d964c8a58f6854f97fe0dea06b100
LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_SOURCE_INCLUDE := .
LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8
LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_ID),$(LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_TYPE),$(LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_BASE_LAYER),$(LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_SOURCE_INCLUDE),$(LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_SOURCE_EXCLUDE),$(LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_CACHE_KEY_FILE),$(LAYER_09-copy-source-e3248ee2d41553d21a812bd2147337ea847e7ae8_ARCHIVE_FILE)))

LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_ID             := 09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944
LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_TYPE           := copy-source
LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_BASE_LAYER     := 08-warm-go-build-vendor-cache-1e8aad7c7e7de30d708ec4149c5dac927e9719c0
LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_SOURCE_INCLUDE := .
LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_SOURCE_EXCLUDE := vendor/ ui/
LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_CACHE_KEY_FILE := .buildcache/cache-keys/copy-source-f8d505897e7aeec79feeadbf467313fd0375b944
LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_ARCHIVE_FILE   := .buildcache/archives/09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944.tar.gz
$(eval $(call LAYER,$(LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_ID),$(LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_TYPE),$(LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_BASE_LAYER),$(LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_SOURCE_INCLUDE),$(LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_SOURCE_EXCLUDE),$(LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_CACHE_KEY_FILE),$(LAYER_09-copy-source-f8d505897e7aeec79feeadbf467313fd0375b944_ARCHIVE_FILE)))
