# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

paths-ignore:
  - '**/*.mdx'      # any file ending in .mdx
  - '**/*.md'       # any file ending in .md
  - '**/*_test.go'  # any file ending in _test.go
