# Copyright IBM Corp. 2016, 2026
# SPDX-License-Identifier: BUSL-1.1

self-hosted-runner:
  # Labels of self-hosted runner in array of string
  labels:
    - small
    - medium
    - large
    - xlarge
    - ubuntu-22.04-x64
    - ubuntu-latest-x64
    - ubuntu-24.04-arm64
    - custom-linux-xl-vault-latest
    - stats
    - type=m6a.8xlarge
