package framework

// knownPathKey consists of an openapi path and its asociated mount path
// (including mount path prefix)
type knownPathKey struct {
	mount string
	path  string
}

// requestResponseParts describes the building parts of a request/response name
//
// In general, the name will be constructed as follows:
//
//	 operation id:  [prefix][operation][suffix]
//	 request name:  [prefix][operation][suffix]Request
//	response name:  [prefix][operation][suffix]Response
//
// Note: if operation is specified, it will overwrite the operation associated
// with the request, which could lead to some collisions
type requestResponseParts struct {
	prefix    string
	operation string
	suffix    string
}

// knownPathMappings is used by constructRequestResponseIdentifier to generate
// more human-readable request/response names in OpenAPI spec
var knownPathMappings = map[knownPathKey]requestResponseParts{
	{mount: "auth/alicloud", path: "login"}:                                            {prefix: "AliCloud", operation: "Login"},
	{mount: "auth/alicloud", path: "role"}:                                             {prefix: "AliCloud", suffix: "AuthRoles"},
	{mount: "auth/alicloud", path: "role/{role}"}:                                      {prefix: "AliCloud", suffix: "AuthRole"},
	{mount: "auth/alicloud", path: "roles"}:                                            {prefix: "AliCloud", suffix: "AuthRoles2"},
	{mount: "auth/approle", path: "login"}:                                             {prefix: "AppRole", operation: "Login"},
	{mount: "auth/approle", path: "role"}:                                              {prefix: "AppRole", suffix: "Roles"},
	{mount: "auth/approle", path: "role/{role_name}"}:                                  {prefix: "AppRole", suffix: "Role"},
	{mount: "auth/approle", path: "role/{role_name}/bind-secret-id"}:                   {prefix: "AppRole", suffix: "BindSecretID"},
	{mount: "auth/approle", path: "role/{role_name}/bound-cidr-list"}:                  {prefix: "AppRole", suffix: "BoundCIDRList"},
	{mount: "auth/approle", path: "role/{role_name}/custom-secret-id"}:                 {prefix: "AppRole", suffix: "CustomSecretID"},
	{mount: "auth/approle", path: "role/{role_name}/local-secret-ids"}:                 {prefix: "AppRole", suffix: "LocalSecretIDs"},
	{mount: "auth/approle", path: "role/{role_name}/period"}:                           {prefix: "AppRole", suffix: "Period"},
	{mount: "auth/approle", path: "role/{role_name}/policies"}:                         {prefix: "AppRole", suffix: "Policies"},
	{mount: "auth/approle", path: "role/{role_name}/role-id"}:                          {prefix: "AppRole", suffix: "RoleID"},
	{mount: "auth/approle", path: "role/{role_name}/secret-id"}:                        {prefix: "AppRole", suffix: "SecretID"},
	{mount: "auth/approle", path: "role/{role_name}/secret-id-accessor/destroy"}:       {prefix: "AppRole", suffix: "SecretIDAccessorDestroy"},
	{mount: "auth/approle", path: "role/{role_name}/secret-id-accessor/lookup"}:        {prefix: "AppRole", suffix: "SecretIDAccessorLookup"},
	{mount: "auth/approle", path: "role/{role_name}/secret-id-bound-cidrs"}:            {prefix: "AppRole", suffix: "SecretIDBoundCIDRs"},
	{mount: "auth/approle", path: "role/{role_name}/secret-id-num-uses"}:               {prefix: "AppRole", suffix: "SecretIDNumUses"},
	{mount: "auth/approle", path: "role/{role_name}/secret-id-ttl"}:                    {prefix: "AppRole", suffix: "SecretIDTTL"},
	{mount: "auth/approle", path: "role/{role_name}/secret-id/destroy"}:                {prefix: "AppRole", suffix: "SecretIDDestroy"},
	{mount: "auth/approle", path: "role/{role_name}/secret-id/lookup"}:                 {prefix: "AppRole", suffix: "SecretIDLookup"},
	{mount: "auth/approle", path: "role/{role_name}/token-bound-cidrs"}:                {prefix: "AppRole", suffix: "TokenBoundCIDRs"},
	{mount: "auth/approle", path: "role/{role_name}/token-max-ttl"}:                    {prefix: "AppRole", suffix: "TokenMaxTTL"},
	{mount: "auth/approle", path: "role/{role_name}/token-num-uses"}:                   {prefix: "AppRole", suffix: "TokenNumUses"},
	{mount: "auth/approle", path: "role/{role_name}/token-ttl"}:                        {prefix: "AppRole", suffix: "TokenTTL"},
	{mount: "auth/approle", path: "tidy/secret-id"}:                                    {prefix: "AppRole", operation: "Tidy", suffix: "SecretID"},
	{mount: "auth/aws", path: "config/certificate/{cert_name}"}:                        {prefix: "AWSConfig", suffix: "Certificate"},
	{mount: "auth/aws", path: "config/certificates"}:                                   {prefix: "AWSConfig", suffix: "Certificates"},
	{mount: "auth/aws", path: "config/client"}:                                         {prefix: "AWSConfig", suffix: "Client"},
	{mount: "auth/aws", path: "config/identity"}:                                       {prefix: "AWSConfig", suffix: "Identity"},
	{mount: "auth/aws", path: "config/rotate-root"}:                                    {prefix: "AWSConfig", suffix: "Root", operation: "Rotate"},
	{mount: "auth/aws", path: "config/sts"}:                                            {prefix: "AWSConfig", suffix: "SecurityTokenService"},
	{mount: "auth/aws", path: "config/sts/{account_id}"}:                               {prefix: "AWSConfig", suffix: "SecurityTokenServiceAccount"},
	{mount: "auth/aws", path: "config/tidy/identity-accesslist"}:                       {prefix: "AWSConfig", suffix: "IdentityAccessList"},
	{mount: "auth/aws", path: "config/tidy/identity-whitelist"}:                        {prefix: "AWSConfig", suffix: "IdentityWhiteList"},
	{mount: "auth/aws", path: "config/tidy/roletag-blacklist"}:                         {prefix: "AWSConfig", suffix: "RoleTagBlackList"},
	{mount: "auth/aws", path: "config/tidy/roletag-denylist"}:                          {prefix: "AWSConfig", suffix: "RoleTagDenyList"},
	{mount: "auth/aws", path: "identity-accesslist"}:                                   {prefix: "AWS", suffix: "IdentityAccessList"},
	{mount: "auth/aws", path: "identity-accesslist/{instance_id}"}:                     {prefix: "AWS", suffix: "IdentityAccessListFor"},
	{mount: "auth/aws", path: "identity-whitelist"}:                                    {prefix: "AWS", suffix: "IdentityWhiteList"},
	{mount: "auth/aws", path: "identity-whitelist/{instance_id}"}:                      {prefix: "AWS", suffix: "IdentityWhiteListFor"},
	{mount: "auth/aws", path: "login"}:                                                 {prefix: "AWS", operation: "Login"},
	{mount: "auth/aws", path: "role"}:                                                  {prefix: "AWS", suffix: "AuthRoles"},
	{mount: "auth/aws", path: "role/{role}"}:                                           {prefix: "AWS", suffix: "AuthRole"},
	{mount: "auth/aws", path: "role/{role}/tag"}:                                       {prefix: "AWS", suffix: "AuthRoleTag"},
	{mount: "auth/aws", path: "roles"}:                                                 {prefix: "AWS", suffix: "AuthRoles2"},
	{mount: "auth/aws", path: "roletag-blacklist"}:                                     {prefix: "AWS", suffix: "RoleTagBlackList"},
	{mount: "auth/aws", path: "roletag-blacklist/{role_tag}"}:                          {prefix: "AWS", suffix: "RoleTagBlackListFor"},
	{mount: "auth/aws", path: "roletag-denylist"}:                                      {prefix: "AWS", suffix: "RoleTagDenyList"},
	{mount: "auth/aws", path: "roletag-denylist/{role_tag}"}:                           {prefix: "AWS", suffix: "RoleTagDenyListFor"},
	{mount: "auth/aws", path: "tidy/identity-accesslist"}:                              {prefix: "AWS", suffix: "IdentityAccessListTidySettings"},
	{mount: "auth/aws", path: "tidy/identity-whitelist"}:                               {prefix: "AWS", suffix: "IdentityWhiteListTidySettings"},
	{mount: "auth/aws", path: "tidy/roletag-blacklist"}:                                {prefix: "AWS", suffix: "RoleTagBlackListTidySettings"},
	{mount: "auth/aws", path: "tidy/roletag-denylist"}:                                 {prefix: "AWS", suffix: "RoleTagDenyListTidySettings"},
	{mount: "auth/azure", path: "config"}:                                              {prefix: "Azure", suffix: "AuthConfig"},
	{mount: "auth/azure", path: "login"}:                                               {prefix: "Azure", operation: "Login"},
	{mount: "auth/azure", path: "role"}:                                                {prefix: "Azure", suffix: "AuthRoles"},
	{mount: "auth/azure", path: "role/{name}"}:                                         {prefix: "Azure", suffix: "AuthRole"},
	{mount: "auth/centrify", path: "config"}:                                           {prefix: "Centrify", suffix: "Config"},
	{mount: "auth/centrify", path: "login"}:                                            {prefix: "Centrify", operation: "Login"},
	{mount: "auth/cert", path: "certs"}:                                                {prefix: "Certificates"},
	{mount: "auth/cert", path: "certs/{name}"}:                                         {prefix: "Certificates"},
	{mount: "auth/cert", path: "config"}:                                               {prefix: "Certificates", suffix: "Config"},
	{mount: "auth/cert", path: "crls"}:                                                 {prefix: "Certificates", suffix: "CRLs"},
	{mount: "auth/cert", path: "crls/{name}"}:                                          {prefix: "Certificates", suffix: "CRL"},
	{mount: "auth/cert", path: "login"}:                                                {prefix: "Certificates", operation: "Login"},
	{mount: "auth/cf", path: "config"}:                                                 {prefix: "CloudFoundry", suffix: "Config"},
	{mount: "auth/cf", path: "login"}:                                                  {prefix: "CloudFoundry", operation: "Login"},
	{mount: "auth/cf", path: "roles"}:                                                  {prefix: "CloudFoundry", suffix: "Roles"},
	{mount: "auth/cf", path: "roles/{role}"}:                                           {prefix: "CloudFoundry", suffix: "Role"},
	{mount: "auth/gcp", path: "config"}:                                                {prefix: "GoogleCloud", suffix: "AuthConfig"},
	{mount: "auth/gcp", path: "login"}:                                                 {prefix: "GoogleCloud", operation: "Login"},
	{mount: "auth/gcp", path: "role"}:                                                  {prefix: "GoogleCloud", suffix: "Roles"},
	{mount: "auth/gcp", path: "role/{name}"}:                                           {prefix: "GoogleCloud", suffix: "Role"},
	{mount: "auth/gcp", path: "role/{name}/labels"}:                                    {prefix: "GoogleCloud", suffix: "RoleLabels"},
	{mount: "auth/gcp", path: "role/{name}/service-accounts"}:                          {prefix: "GoogleCloud", suffix: "RoleServiceAccounts"},
	{mount: "auth/gcp", path: "roles"}:                                                 {prefix: "GoogleCloud", suffix: "Roles2"},
	{mount: "auth/github", path: "config"}:                                             {prefix: "GitHub", suffix: "Config"},
	{mount: "auth/github", path: "login"}:                                              {prefix: "GitHub", operation: "Login"},
	{mount: "auth/github", path: "map/teams"}:                                          {prefix: "GitHub", suffix: "MapTeams"},
	{mount: "auth/github", path: "map/teams/{key}"}:                                    {prefix: "GitHub", suffix: "MapTeam"},
	{mount: "auth/github", path: "map/users"}:                                          {prefix: "GitHub", suffix: "MapUsers"},
	{mount: "auth/github", path: "map/users/{key}"}:                                    {prefix: "GitHub", suffix: "MapUser"},
	{mount: "auth/jwt", path: "config"}:                                                {prefix: "JWT", suffix: "Config"},
	{mount: "auth/jwt", path: "login"}:                                                 {prefix: "JWT", operation: "Login"},
	{mount: "auth/jwt", path: "oidc/auth_url"}:                                         {prefix: "JWT", suffix: "OIDCAuthURL"},
	{mount: "auth/jwt", path: "oidc/callback"}:                                         {prefix: "JWT", suffix: "OIDCCallback"},
	{mount: "auth/jwt", path: "role"}:                                                  {prefix: "JWT", suffix: "Roles"},
	{mount: "auth/jwt", path: "role/{name}"}:                                           {prefix: "JWT", suffix: "Role"},
	{mount: "auth/kerberos", path: "config"}:                                           {prefix: "Kerberos", suffix: "Config"},
	{mount: "auth/kerberos", path: "config/ldap"}:                                      {prefix: "Kerberos", suffix: "LDAPConfig"},
	{mount: "auth/kerberos", path: "groups"}:                                           {prefix: "Kerberos", suffix: "Groups"},
	{mount: "auth/kerberos", path: "groups/{name}"}:                                    {prefix: "Kerberos", suffix: "Group"},
	{mount: "auth/kerberos", path: "login"}:                                            {prefix: "Kerberos", operation: "Login"},
	{mount: "auth/kubernetes", path: "config"}:                                         {prefix: "Kubernetes", suffix: "AuthConfig"},
	{mount: "auth/kubernetes", path: "login"}:                                          {prefix: "Kubernetes", operation: "Login"},
	{mount: "auth/kubernetes", path: "role"}:                                           {prefix: "Kubernetes", suffix: "AuthRoles"},
	{mount: "auth/kubernetes", path: "role/{name}"}:                                    {prefix: "Kubernetes", suffix: "AuthRole"},
	{mount: "auth/ldap", path: "config"}:                                               {prefix: "LDAP", suffix: "AuthConfig"},
	{mount: "auth/ldap", path: "groups"}:                                               {prefix: "LDAP", suffix: "Groups"},
	{mount: "auth/ldap", path: "groups/{name}"}:                                        {prefix: "LDAP", suffix: "Group"},
	{mount: "auth/ldap", path: "login/{username}"}:                                     {prefix: "LDAP", operation: "Login"},
	{mount: "auth/ldap", path: "users"}:                                                {prefix: "LDAP", suffix: "Users"},
	{mount: "auth/ldap", path: "users/{name}"}:                                         {prefix: "LDAP", suffix: "User"},
	{mount: "auth/oci", path: "config"}:                                                {prefix: "OCI", suffix: "Config"},
	{mount: "auth/oci", path: "login"}:                                                 {prefix: "OCI", operation: "Login"},
	{mount: "auth/oci", path: "login/{role}"}:                                          {prefix: "OCI", operation: "Login", suffix: "WithRole"},
	{mount: "auth/oci", path: "role"}:                                                  {prefix: "OCI", suffix: "Roles"},
	{mount: "auth/oci", path: "role/{role}"}:                                           {prefix: "OCI", suffix: "Role"},
	{mount: "auth/oidc", path: "config"}:                                               {prefix: "OIDC", suffix: "AuthConfig"},
	{mount: "auth/oidc", path: "login"}:                                                {prefix: "OIDC", operation: "Login"},
	{mount: "auth/oidc", path: "oidc/auth_url"}:                                        {prefix: "OIDC", suffix: "AuthURL"},
	{mount: "auth/oidc", path: "oidc/callback"}:                                        {prefix: "OIDC", suffix: "Callback"},
	{mount: "auth/oidc", path: "role"}:                                                 {prefix: "OIDC", suffix: "AuthRoles"},
	{mount: "auth/oidc", path: "role/{name}"}:                                          {prefix: "OIDC", suffix: "AuthRole"},
	{mount: "auth/okta", path: "config"}:                                               {prefix: "Okta", suffix: "Config"},
	{mount: "auth/okta", path: "groups"}:                                               {prefix: "Okta", suffix: "Groups"},
	{mount: "auth/okta", path: "groups/{name}"}:                                        {prefix: "Okta", suffix: "Group"},
	{mount: "auth/okta", path: "login/{username}"}:                                     {prefix: "Okta", operation: "Login"},
	{mount: "auth/okta", path: "users"}:                                                {prefix: "Okta", suffix: "Users"},
	{mount: "auth/okta", path: "users/{name}"}:                                         {prefix: "Okta", suffix: "User"},
	{mount: "auth/okta", path: "verify/{nonce}"}:                                       {prefix: "Okta", operation: "Verify"},
	{mount: "auth/radius", path: "config"}:                                             {prefix: "Radius", suffix: "Config"},
	{mount: "auth/radius", path: "login"}:                                              {prefix: "Radius", operation: "Login"},
	{mount: "auth/radius", path: "login/{urlusername}"}:                                {prefix: "Radius", operation: "Login", suffix: "WithUsername"},
	{mount: "auth/radius", path: "users"}:                                              {prefix: "Radius", suffix: "Users"},
	{mount: "auth/radius", path: "users/{name}"}:                                       {prefix: "Radius", suffix: "User"},
	{mount: "auth/token", path: "accessors/"}:                                          {prefix: "Token", suffix: "Accessors"},
	{mount: "auth/token", path: "create"}:                                              {prefix: "Token", suffix: "Create"},
	{mount: "auth/token", path: "create-orphan"}:                                       {prefix: "Token", suffix: "CreateOrphan"},
	{mount: "auth/token", path: "create/{role_name}"}:                                  {prefix: "Token", suffix: "CreateWithRole"},
	{mount: "auth/token", path: "lookup"}:                                              {prefix: "Token", suffix: "Lookup"},
	{mount: "auth/token", path: "lookup-accessor"}:                                     {prefix: "Token", suffix: "LookupAccessor"},
	{mount: "auth/token", path: "lookup-self"}:                                         {prefix: "Token", suffix: "LookupSelf"},
	{mount: "auth/token", path: "renew"}:                                               {prefix: "Token", operation: "Renew"},
	{mount: "auth/token", path: "renew-accessor"}:                                      {prefix: "Token", operation: "Renew", suffix: "Accessor"},
	{mount: "auth/token", path: "renew-self"}:                                          {prefix: "Token", operation: "Renew", suffix: "Self"},
	{mount: "auth/token", path: "revoke"}:                                              {prefix: "Token", operation: "Revoke"},
	{mount: "auth/token", path: "revoke-accessor"}:                                     {prefix: "Token", operation: "Revoke", suffix: "Accessor"},
	{mount: "auth/token", path: "revoke-orphan"}:                                       {prefix: "Token", operation: "Revoke", suffix: "Orphan"},
	{mount: "auth/token", path: "revoke-self"}:                                         {prefix: "Token", operation: "Revoke", suffix: "Self"},
	{mount: "auth/token", path: "roles"}:                                               {prefix: "Token", suffix: "Roles"},
	{mount: "auth/token", path: "roles/{role_name}"}:                                   {prefix: "Token", suffix: "Role"},
	{mount: "auth/token", path: "tidy"}:                                                {prefix: "Token", operation: "Tidy"},
	{mount: "auth/userpass", path: "login/{username}"}:                                 {prefix: "Userpass", operation: "Login"},
	{mount: "auth/userpass", path: "users"}:                                            {prefix: "Userpass", suffix: "Users"},
	{mount: "auth/userpass", path: "users/{username}"}:                                 {prefix: "Userpass", suffix: "User"},
	{mount: "auth/userpass", path: "users/{username}/password"}:                        {prefix: "Userpass", suffix: "UserPassword"},
	{mount: "auth/userpass", path: "users/{username}/policies"}:                        {prefix: "Userpass", suffix: "UserPolicies"},
	{mount: "ad", path: "config"}:                                                      {prefix: "ActiveDirectory", suffix: "Config"},
	{mount: "ad", path: "creds/{name}"}:                                                {prefix: "ActiveDirectory", suffix: "Credentials"},
	{mount: "ad", path: "library"}:                                                     {prefix: "ActiveDirectory", suffix: "Libraries"},
	{mount: "ad", path: "library/manage/{name}/check-in"}:                              {prefix: "ActiveDirectory", suffix: "Library", operation: "CheckInManage"},
	{mount: "ad", path: "library/{name}"}:                                              {prefix: "ActiveDirectory", suffix: "Library"},
	{mount: "ad", path: "library/{name}/check-in"}:                                     {prefix: "ActiveDirectory", suffix: "Library", operation: "CheckIn"},
	{mount: "ad", path: "library/{name}/check-out"}:                                    {prefix: "ActiveDirectory", suffix: "Library", operation: "CheckOut"},
	{mount: "ad", path: "library/{name}/status"}:                                       {prefix: "ActiveDirectory", suffix: "LibraryStatus"},
	{mount: "ad", path: "roles"}:                                                       {prefix: "ActiveDirectory", suffix: "Roles"},
	{mount: "ad", path: "roles/{name}"}:                                                {prefix: "ActiveDirectory", suffix: "Role"},
	{mount: "ad", path: "rotate-role/{name}"}:                                          {prefix: "ActiveDirectory", suffix: "Role", operation: "Rotate"},
	{mount: "ad", path: "rotate-root"}:                                                 {prefix: "ActiveDirectory", suffix: "Root", operation: "Rotate"},
	{mount: "alicloud", path: "config"}:                                                {prefix: "AliCloud", suffix: "Config"},
	{mount: "alicloud", path: "creds/{name}"}:                                          {prefix: "AliCloud", suffix: "Credentials"},
	{mount: "alicloud", path: "role"}:                                                  {prefix: "AliCloud", suffix: "Roles"},
	{mount: "alicloud", path: "role/{name}"}:                                           {prefix: "AliCloud", suffix: "Role"},
	{mount: "aws", path: "config/lease"}:                                               {prefix: "AWSConfig", suffix: "Lease"},
	{mount: "aws", path: "config/root"}:                                                {prefix: "AWSConfig", suffix: "RootIAMCredentials"},
	{mount: "aws", path: "config/rotate-root"}:                                         {prefix: "AWSConfig", suffix: "RootIAMCredentials", operation: "Rotate"},
	{mount: "aws", path: "creds"}:                                                      {prefix: "AWS", suffix: "Credentials"},
	{mount: "aws", path: "roles"}:                                                      {prefix: "AWS", suffix: "Roles"},
	{mount: "aws", path: "roles/{name}"}:                                               {prefix: "AWS", suffix: "Role"},
	{mount: "aws", path: "sts/{name}"}:                                                 {prefix: "AWS", suffix: "SecurityTokenService"},
	{mount: "azure", path: "config"}:                                                   {prefix: "Azure", suffix: "Config"},
	{mount: "azure", path: "creds/{role}"}:                                             {prefix: "Azure", suffix: "Credentials"},
	{mount: "azure", path: "roles"}:                                                    {prefix: "Azure", suffix: "Roles"},
	{mount: "azure", path: "roles/{name}"}:                                             {prefix: "Azure", suffix: "Role"},
	{mount: "azure", path: "rotate-root"}:                                              {prefix: "Azure", suffix: "Root", operation: "Rotate"},
	{mount: "consul", path: "config/access"}:                                           {prefix: "Consul", suffix: "AccessConfig"},
	{mount: "consul", path: "creds/{role}"}:                                            {prefix: "Consul", suffix: "Credentials"},
	{mount: "consul", path: "roles"}:                                                   {prefix: "Consul", suffix: "Roles"},
	{mount: "consul", path: "roles/{name}"}:                                            {prefix: "Consul", suffix: "Role"},
	{mount: "cubbyhole", path: "{path}"}:                                               {prefix: "Cubbyhole"},
	{mount: "gcp", path: "config"}:                                                     {prefix: "GoogleCloud", suffix: "Config"},
	{mount: "gcp", path: "config/rotate-root"}:                                         {prefix: "GoogleCloud", operation: "Rotate", suffix: "Root"},
	{mount: "gcp", path: "key/{roleset}"}:                                              {prefix: "GoogleCloud", suffix: "Key"},
	{mount: "gcp", path: "roleset/{name}"}:                                             {prefix: "GoogleCloud", suffix: "Roleset"},
	{mount: "gcp", path: "roleset/{name}/rotate"}:                                      {prefix: "GoogleCloud", suffix: "Roleset", operation: "Rotate"},
	{mount: "gcp", path: "roleset/{name}/rotate-key"}:                                  {prefix: "GoogleCloud", suffix: "RolesetKey", operation: "Rotate"},
	{mount: "gcp", path: "roleset/{roleset}/key"}:                                      {prefix: "GoogleCloud", suffix: "RolesetKey"},
	{mount: "gcp", path: "roleset/{roleset}/token"}:                                    {prefix: "GoogleCloud", suffix: "RolesetToken"},
	{mount: "gcp", path: "rolesets"}:                                                   {prefix: "GoogleCloud", suffix: "Rolesets"},
	{mount: "gcp", path: "static-account/{name}"}:                                      {prefix: "GoogleCloud", suffix: "StaticAccount"},
	{mount: "gcp", path: "static-account/{name}/key"}:                                  {prefix: "GoogleCloud", suffix: "StaticAccountKey"},
	{mount: "gcp", path: "static-account/{name}/rotate-key"}:                           {prefix: "GoogleCloud", suffix: "StaticAccountKey", operation: "Rotate"},
	{mount: "gcp", path: "static-account/{name}/token"}:                                {prefix: "GoogleCloud", suffix: "StaticAccountToken"},
	{mount: "gcp", path: "static-accounts"}:                                            {prefix: "GoogleCloud", suffix: "StaticAccounts"},
	{mount: "gcp", path: "token/{roleset}"}:                                            {prefix: "GoogleCloud", suffix: "Token"},
	{mount: "gcpkms", path: "config"}:                                                  {prefix: "GoogleCloudKMS", suffix: "Config"},
	{mount: "gcpkms", path: "decrypt/{key}"}:                                           {prefix: "GoogleCloudKMS", operation: "Decrypt"},
	{mount: "gcpkms", path: "encrypt/{key}"}:                                           {prefix: "GoogleCloudKMS", operation: "Encrypt"},
	{mount: "gcpkms", path: "keys"}:                                                    {prefix: "GoogleCloudKMS", suffix: "Keys"},
	{mount: "gcpkms", path: "keys/config/{key}"}:                                       {prefix: "GoogleCloudKMS", suffix: "KeyConfig"},
	{mount: "gcpkms", path: "keys/deregister/{key}"}:                                   {prefix: "GoogleCloudKMS", suffix: "Key", operation: "Deregister"},
	{mount: "gcpkms", path: "keys/register/{key}"}:                                     {prefix: "GoogleCloudKMS", suffix: "Key", operation: "Register"},
	{mount: "gcpkms", path: "keys/rotate/{key}"}:                                       {prefix: "GoogleCloudKMS", suffix: "Key", operation: "Rotate"},
	{mount: "gcpkms", path: "keys/trim/{key}"}:                                         {prefix: "GoogleCloudKMS", suffix: "Key", operation: "Trim"},
	{mount: "gcpkms", path: "keys/{key}"}:                                              {prefix: "GoogleCloudKMS", suffix: "Key"},
	{mount: "gcpkms", path: "pubkey/{key}"}:                                            {prefix: "GoogleCloudKMS", suffix: "Pubkey"},
	{mount: "gcpkms", path: "reencrypt/{key}"}:                                         {prefix: "GoogleCloudKMS", operation: "Reencrypt"},
	{mount: "gcpkms", path: "sign/{key}"}:                                              {prefix: "GoogleCloudKMS", operation: "Sign"},
	{mount: "gcpkms", path: "verify/{key}"}:                                            {prefix: "GoogleCloudKMS", operation: "Verify"},
	{mount: "identity", path: "alias"}:                                                 {prefix: "Alias"},
	{mount: "identity", path: "alias/id"}:                                              {prefix: "Alias", suffix: "ByID"},
	{mount: "identity", path: "alias/id/{id}"}:                                         {prefix: "Alias", suffix: "ByID"},
	{mount: "identity", path: "entity"}:                                                {prefix: "Entity"},
	{mount: "identity", path: "entity-alias"}:                                          {prefix: "Entity", suffix: "Alias"},
	{mount: "identity", path: "entity-alias/id"}:                                       {prefix: "Entity", suffix: "AliasesByID"},
	{mount: "identity", path: "entity-alias/id/{id}"}:                                  {prefix: "Entity", suffix: "AliasByID"},
	{mount: "identity", path: "entity/batch-delete"}:                                   {prefix: "Entity", operation: "BatchDelete"},
	{mount: "identity", path: "entity/id"}:                                             {prefix: "Entity", suffix: "ByID"},
	{mount: "identity", path: "entity/id/{id}"}:                                        {prefix: "Entity", suffix: "ByID"},
	{mount: "identity", path: "entity/merge"}:                                          {prefix: "Entity", operation: "Merge"},
	{mount: "identity", path: "entity/name"}:                                           {prefix: "Entity", suffix: "ByName"},
	{mount: "identity", path: "entity/name/{name}"}:                                    {prefix: "Entity", suffix: "ByName"},
	{mount: "identity", path: "group"}:                                                 {prefix: "Group"},
	{mount: "identity", path: "group-alias"}:                                           {prefix: "Group", suffix: "Alias"},
	{mount: "identity", path: "group-alias/id"}:                                        {prefix: "Group", suffix: "AliasesByID"},
	{mount: "identity", path: "group-alias/id/{id}"}:                                   {prefix: "Group", suffix: "AliasByID"},
	{mount: "identity", path: "group/id"}:                                              {prefix: "Group", suffix: "ByID"},
	{mount: "identity", path: "group/id/{id}"}:                                         {prefix: "Group", suffix: "ByID"},
	{mount: "identity", path: "group/name"}:                                            {prefix: "Group", suffix: "ByName"},
	{mount: "identity", path: "group/name/{name}"}:                                     {prefix: "Group", suffix: "ByName"},
	{mount: "identity", path: "lookup/entity"}:                                         {prefix: "Entity", operation: "Lookup"},
	{mount: "identity", path: "lookup/group"}:                                          {prefix: "Group", operation: "Lookup"},
	{mount: "identity", path: "mfa/login-enforcement"}:                                 {prefix: "MFA", suffix: "LoginEnforcements"},
	{mount: "identity", path: "mfa/login-enforcement/{name}"}:                          {prefix: "MFA", suffix: "LoginEnforcement"},
	{mount: "identity", path: "mfa/method"}:                                            {prefix: "MFAMethod"},
	{mount: "identity", path: "mfa/method/duo"}:                                        {prefix: "MFAMethod", suffix: "Duo"},
	{mount: "identity", path: "mfa/method/duo/{method_id}"}:                            {prefix: "MFAMethod", suffix: "Duo"},
	{mount: "identity", path: "mfa/method/okta"}:                                       {prefix: "MFAMethod", suffix: "Okta"},
	{mount: "identity", path: "mfa/method/okta/{method_id}"}:                           {prefix: "MFAMethod", suffix: "Okta"},
	{mount: "identity", path: "mfa/method/pingid"}:                                     {prefix: "MFAMethod", suffix: "PingID"},
	{mount: "identity", path: "mfa/method/pingid/{method_id}"}:                         {prefix: "MFAMethod", suffix: "PingID"},
	{mount: "identity", path: "mfa/method/totp"}:                                       {prefix: "MFAMethod", suffix: "TOTP"},
	{mount: "identity", path: "mfa/method/totp/admin-destroy"}:                         {prefix: "MFAMethod", suffix: "TOTP", operation: "AdminDestroy"},
	{mount: "identity", path: "mfa/method/totp/admin-generate"}:                        {prefix: "MFAMethod", suffix: "TOTP", operation: "AdminGenerate"},
	{mount: "identity", path: "mfa/method/totp/generate"}:                              {prefix: "MFAMethod", suffix: "TOTP", operation: "Generate"},
	{mount: "identity", path: "mfa/method/totp/{method_id}"}:                           {prefix: "MFAMethod", suffix: "TOTP"},
	{mount: "identity", path: "mfa/method/{method_id}"}:                                {prefix: "MFAMethod"},
	{mount: "identity", path: "oidc/.well-known/keys"}:                                 {prefix: "OIDC", suffix: "WellKnownKeys"},
	{mount: "identity", path: "oidc/.well-known/openid-configuration"}:                 {prefix: "OIDC", suffix: "WellKnownOpenIDConfiguration"},
	{mount: "identity", path: "oidc/assignment"}:                                       {prefix: "OIDC", suffix: "Assignments"},
	{mount: "identity", path: "oidc/assignment/{name}"}:                                {prefix: "OIDC", suffix: "Assignment"},
	{mount: "identity", path: "oidc/client"}:                                           {prefix: "OIDC", suffix: "Clients"},
	{mount: "identity", path: "oidc/client/{name}"}:                                    {prefix: "OIDC", suffix: "Client"},
	{mount: "identity", path: "oidc/config"}:                                           {prefix: "OIDC", suffix: "Config"},
	{mount: "identity", path: "oidc/introspect"}:                                       {prefix: "OIDC", operation: "Introspect"},
	{mount: "identity", path: "oidc/key"}:                                              {prefix: "OIDC", suffix: "Keys"},
	{mount: "identity", path: "oidc/key/{name}"}:                                       {prefix: "OIDC", suffix: "Key"},
	{mount: "identity", path: "oidc/key/{name}/rotate"}:                                {prefix: "OIDC", suffix: "Key", operation: "Rotate"},
	{mount: "identity", path: "oidc/provider"}:                                         {prefix: "OIDC", suffix: "Providers"},
	{mount: "identity", path: "oidc/provider/{name}"}:                                  {prefix: "OIDC", suffix: "Provider"},
	{mount: "identity", path: "oidc/provider/{name}/.well-known/keys"}:                 {prefix: "OIDC", suffix: "ProviderWellKnownKeys"},
	{mount: "identity", path: "oidc/provider/{name}/.well-known/openid-configuration"}: {prefix: "OIDC", suffix: "ProviderWellKnownOpenIDConfiguration"},
	{mount: "identity", path: "oidc/provider/{name}/authorize"}:                        {prefix: "OIDC", suffix: "ProviderAuthorize"},
	{mount: "identity", path: "oidc/provider/{name}/token"}:                            {prefix: "OIDC", suffix: "ProviderToken"},
	{mount: "identity", path: "oidc/provider/{name}/userinfo"}:                         {prefix: "OIDC", suffix: "ProviderUserInfo"},
	{mount: "identity", path: "oidc/role"}:                                             {prefix: "OIDC", suffix: "Roles"},
	{mount: "identity", path: "oidc/role/{name}"}:                                      {prefix: "OIDC", suffix: "Role"},
	{mount: "identity", path: "oidc/scope"}:                                            {prefix: "OIDC", suffix: "Scopes"},
	{mount: "identity", path: "oidc/scope/{name}"}:                                     {prefix: "OIDC", suffix: "Scope"},
	{mount: "identity", path: "oidc/token/{name}"}:                                     {prefix: "OIDC", suffix: "Token"},
	{mount: "identity", path: "persona"}:                                               {prefix: "Persona"},
	{mount: "identity", path: "persona/id"}:                                            {prefix: "Persona", suffix: "ByID"},
	{mount: "identity", path: "persona/id/{id}"}:                                       {prefix: "PersonaID", suffix: "ByID"},
	{mount: "kubernetes", path: "config"}:                                              {prefix: "Kubernetes", suffix: "Config"},
	{mount: "kubernetes", path: "creds/{name}"}:                                        {prefix: "Kubernetes", suffix: "Credentials"},
	{mount: "kubernetes", path: "roles"}:                                               {prefix: "Kubernetes", suffix: "Roles"},
	{mount: "kubernetes", path: "roles/{name}"}:                                        {prefix: "Kubernetes", suffix: "Role"},
	{mount: "kv", path: "{path}"}:                                                      {prefix: "KVv1"},
	{mount: "ldap", path: "config"}:                                                    {prefix: "LDAP", suffix: "Config"},
	{mount: "ldap", path: "creds/{name}"}:                                              {prefix: "LDAP", suffix: "Credentials"},
	{mount: "ldap", path: "library"}:                                                   {prefix: "LDAP", suffix: "Libraries"},
	{mount: "ldap", path: "library/manage/{name}/check-in"}:                            {prefix: "LDAP", suffix: "Library", operation: "CheckInManage"},
	{mount: "ldap", path: "library/{name}"}:                                            {prefix: "LDAP", suffix: "Library"},
	{mount: "ldap", path: "library/{name}/check-in"}:                                   {prefix: "LDAP", suffix: "Library", operation: "CheckIn"},
	{mount: "ldap", path: "library/{name}/check-out"}:                                  {prefix: "LDAP", suffix: "Library", operation: "CheckOut"},
	{mount: "ldap", path: "library/{name}/status"}:                                     {prefix: "LDAP", suffix: "LibraryStatus"},
	{mount: "ldap", path: "role"}:                                                      {prefix: "LDAP", suffix: "Roles"},
	{mount: "ldap", path: "role/{name}"}:                                               {prefix: "LDAP", suffix: "Role"},
	{mount: "ldap", path: "rotate-role/{name}"}:                                        {prefix: "LDAP", suffix: "Role", operation: "Rotate"},
	{mount: "ldap", path: "rotate-root"}:                                               {prefix: "LDAP", suffix: "Root", operation: "Rotate"},
	{mount: "ldap", path: "static-cred/{name}"}:                                        {prefix: "LDAP", suffix: "StaticCredentials"},
	{mount: "ldap", path: "static-role"}:                                               {prefix: "LDAP", suffix: "StaticRoles"},
	{mount: "ldap", path: "static-role/{name}"}:                                        {prefix: "LDAP", suffix: "StaticRole"},
	{mount: "mongodbatlas", path: "config"}:                                            {prefix: "MongoDBAtlas", suffix: "Config"},
	{mount: "mongodbatlas", path: "creds/{name}"}:                                      {prefix: "MongoDBAtlas", suffix: "Credentials"},
	{mount: "mongodbatlas", path: "roles"}:                                             {prefix: "MongoDBAtlas", suffix: "Roles"},
	{mount: "mongodbatlas", path: "roles/{name}"}:                                      {prefix: "MongoDBAtlas", suffix: "Role"},
	{mount: "nomad", path: "config/access"}:                                            {prefix: "Nomad", suffix: "AccessConfig"},
	{mount: "nomad", path: "config/lease"}:                                             {prefix: "Nomad", suffix: "LeaseConfig"},
	{mount: "nomad", path: "creds/{name}"}:                                             {prefix: "Nomad", suffix: "Credentials"},
	{mount: "nomad", path: "role"}:                                                     {prefix: "Nomad", suffix: "Roles"},
	{mount: "nomad", path: "role/{name}"}:                                              {prefix: "Nomad", suffix: "Role"},
	{mount: "openldap", path: "config"}:                                                {prefix: "OpenLDAP", suffix: "Config"},
	{mount: "openldap", path: "creds/{name}"}:                                          {prefix: "OpenLDAP", suffix: "Credentials"},
	{mount: "openldap", path: "library"}:                                               {prefix: "OpenLDAP", suffix: "Libraries"},
	{mount: "openldap", path: "library/manage/{name}/check-in"}:                        {prefix: "OpenLDAP", suffix: "Library", operation: "CheckInManage"},
	{mount: "openldap", path: "library/{name}"}:                                        {prefix: "OpenLDAP", suffix: "Library"},
	{mount: "openldap", path: "library/{name}/check-in"}:                               {prefix: "OpenLDAP", suffix: "Library", operation: "CheckIn"},
	{mount: "openldap", path: "library/{name}/check-out"}:                              {prefix: "OpenLDAP", suffix: "Library", operation: "CheckOut"},
	{mount: "openldap", path: "library/{name}/status"}:                                 {prefix: "OpenLDAP", suffix: "LibraryStatus"},
	{mount: "openldap", path: "role"}:                                                  {prefix: "OpenLDAP", suffix: "Roles"},
	{mount: "openldap", path: "role/{name}"}:                                           {prefix: "OpenLDAP", suffix: "Role"},
	{mount: "openldap", path: "rotate-role/{name}"}:                                    {prefix: "OpenLDAP", suffix: "Role", operation: "Rotate"},
	{mount: "openldap", path: "rotate-root"}:                                           {prefix: "OpenLDAP", suffix: "Root", operation: "Rotate"},
	{mount: "openldap", path: "static-cred/{name}"}:                                    {prefix: "OpenLDAP", suffix: "StaticCredentials"},
	{mount: "openldap", path: "static-role"}:                                           {prefix: "OpenLDAP", suffix: "StaticRoles"},
	{mount: "openldap", path: "static-role/{name}"}:                                    {prefix: "OpenLDAP", suffix: "StaticRole"},
	{mount: "pki", path: "bundle"}:                                                     {prefix: "PKIBundle"},
	{mount: "pki", path: "ca"}:                                                         {prefix: "PKI", suffix: "CA"},
	{mount: "pki", path: "ca/pem"}:                                                     {prefix: "PKI", suffix: "CAPem"},
	{mount: "pki", path: "ca_chain"}:                                                   {prefix: "PKI", suffix: "CAChain"},
	{mount: "pki", path: "cert"}:                                                       {prefix: "PKI", suffix: "Certs"},
	{mount: "pki", path: "cert/ca_chain"}:                                              {prefix: "PKI", suffix: "CertCAChain"},
	{mount: "pki", path: "cert/{serial}"}:                                              {prefix: "PKI", suffix: "Cert"},
	{mount: "pki", path: "cert/{serial}/raw"}:                                          {prefix: "PKI", suffix: "CertRaw"},
	{mount: "pki", path: "cert/{serial}/raw/pem"}:                                      {prefix: "PKI", suffix: "CertRawPem"},
	{mount: "pki", path: "certs"}:                                                      {prefix: "PKI", suffix: "Certs"},
	{mount: "pki", path: "certs/revoked"}:                                              {prefix: "PKI", suffix: "CertsRevoked"},
	{mount: "pki", path: "config/auto-tidy"}:                                           {prefix: "PKI", suffix: "AutoTidyConfig"},
	{mount: "pki", path: "config/ca"}:                                                  {prefix: "PKI", suffix: "CAConfig"},
	{mount: "pki", path: "config/cluster"}:                                             {prefix: "PKI", suffix: "ClusterConfig"},
	{mount: "pki", path: "config/crl"}:                                                 {prefix: "PKI", suffix: "CRLConfig"},
	{mount: "pki", path: "config/issuers"}:                                             {prefix: "PKI", suffix: "IssuersConfig"},
	{mount: "pki", path: "config/keys"}:                                                {prefix: "PKI", suffix: "KeysConfig"},
	{mount: "pki", path: "config/urls"}:                                                {prefix: "PKI", suffix: "URLConfig"},
	{mount: "pki", path: "crl"}:                                                        {prefix: "PKI", suffix: "CRL"},
	{mount: "pki", path: "crl/rotate"}:                                                 {prefix: "PKI", suffix: "CRLRotate"},
	{mount: "pki", path: "crl/rotate-delta"}:                                           {prefix: "PKI", suffix: "CRLRotateDelta"},
	{mount: "pki", path: "delta-crl"}:                                                  {prefix: "PKI", suffix: "DeltaCRL"},
	{mount: "pki", path: "intermediate/cross-sign"}:                                    {prefix: "PKI", suffix: "IntermediateCrossSign"},
	{mount: "pki", path: "intermediate/generate/{exported}"}:                           {prefix: "PKI", suffix: "IntermediateGenerate"},
	{mount: "pki", path: "intermediate/set-signed"}:                                    {prefix: "PKI", suffix: "IntermediateSetSigned"},
	{mount: "pki", path: "internal|exported"}:                                          {prefix: "PKI", suffix: "InternalExported"},
	{mount: "pki", path: "issue/{role}"}:                                               {prefix: "PKI", suffix: "IssueRole"},
	{mount: "pki", path: "issuer/{issuer_ref}/issue/{role}"}:                           {prefix: "PKIIssuer", operation: "Issue", suffix: "Role"},
	{mount: "pki", path: "issuer/{issuer_ref}/resign-crls"}:                            {prefix: "PKIIssuer", operation: "Resign", suffix: "CRLs"},
	{mount: "pki", path: "issuer/{issuer_ref}/revoke"}:                                 {prefix: "PKIIssuer", operation: "Revoke"},
	{mount: "pki", path: "issuer/{issuer_ref}/sign-intermediate"}:                      {prefix: "PKIIssuer", operation: "Sign", suffix: "Intermediate"},
	{mount: "pki", path: "issuer/{issuer_ref}/sign-revocation-list"}:                   {prefix: "PKIIssuer", operation: "Sign", suffix: "RevocationList"},
	{mount: "pki", path: "issuer/{issuer_ref}/sign-self-issued"}:                       {prefix: "PKIIssuer", operation: "Sign", suffix: "SelfIssued"},
	{mount: "pki", path: "issuer/{issuer_ref}/sign-verbatim"}:                          {prefix: "PKIIssuer", operation: "Sign", suffix: "Verbatim"},
	{mount: "pki", path: "issuer/{issuer_ref}/sign-verbatim/{role}"}:                   {prefix: "PKIIssuer", operation: "Sign", suffix: "VerbatimRole"},
	{mount: "pki", path: "issuer/{issuer_ref}/sign/{role}"}:                            {prefix: "PKIIssuer", operation: "Sign", suffix: "Role"},
	{mount: "pki", path: "issuers"}:                                                    {prefix: "PKIIssuers"},
	{mount: "pki", path: "issuers/generate/intermediate/{exported}"}:                   {prefix: "PKIIssuers", operation: "GenerateIntermediate"},
	{mount: "pki", path: "issuers/generate/root/{exported}"}:                           {prefix: "PKIIssuers", operation: "GenerateRoot"},
	{mount: "pki", path: "key/{key_ref}"}:                                              {prefix: "PKI", suffix: "Key"},
	{mount: "pki", path: "keys"}:                                                       {prefix: "PKI", suffix: "Keys"},
	{mount: "pki", path: "keys/import"}:                                                {prefix: "PKI", suffix: "Keys", operation: "Import"},
	{mount: "pki", path: "kms"}:                                                        {prefix: "PKI", suffix: "KMS"},
	{mount: "pki", path: "ocsp"}:                                                       {prefix: "PKI", suffix: "OCSP"},
	{mount: "pki", path: "ocsp/{req}"}:                                                 {prefix: "PKI", suffix: "OCSPReq"},
	{mount: "pki", path: "revoke"}:                                                     {prefix: "PKI", operation: "Revoke"},
	{mount: "pki", path: "revoke-with-key"}:                                            {prefix: "PKI", operation: "Revoke", suffix: "WithKey"},
	{mount: "pki", path: "roles"}:                                                      {prefix: "PKI", suffix: "Roles"},
	{mount: "pki", path: "roles/{name}"}:                                               {prefix: "PKI", suffix: "Role"},
	{mount: "pki", path: "root"}:                                                       {prefix: "PKI", suffix: "Root"},
	{mount: "pki", path: "root/generate/{exported}"}:                                   {prefix: "PKI", suffix: "Root", operation: "Generate"},
	{mount: "pki", path: "root/replace"}:                                               {prefix: "PKI", suffix: "Root", operation: "Replace"},
	{mount: "pki", path: "root/rotate/{exported}"}:                                     {prefix: "PKI", suffix: "Root", operation: "Rotate"},
	{mount: "pki", path: "root/sign-intermediate"}:                                     {prefix: "PKI", operation: "RootSignIntermediate"},
	{mount: "pki", path: "root/sign-self-issued"}:                                      {prefix: "PKI", operation: "RootSignSelfIssued"},
	{mount: "pki", path: "sign-verbatim"}:                                              {prefix: "PKI", operation: "SignVerbatim"},
	{mount: "pki", path: "sign-verbatim/{role}"}:                                       {prefix: "PKI", operation: "SignVerbatim", suffix: "Role"},
	{mount: "pki", path: "sign/{role}"}:                                                {prefix: "PKI", operation: "Sign", suffix: "Role"},
	{mount: "pki", path: "tidy"}:                                                       {prefix: "PKI", operation: "Tidy"},
	{mount: "pki", path: "tidy-cancel"}:                                                {prefix: "PKI", operation: "TidyCancel"},
	{mount: "pki", path: "tidy-status"}:                                                {prefix: "PKI", operation: "TidyStatus"},
	{mount: "rabbitmq", path: "config/connection"}:                                     {prefix: "RabbitMQ", suffix: "ConnectionConfig"},
	{mount: "rabbitmq", path: "config/lease"}:                                          {prefix: "RabbitMQ", suffix: "LeaseConfig"},
	{mount: "rabbitmq", path: "creds/{name}"}:                                          {prefix: "RabbitMQ", suffix: "Credentials"},
	{mount: "rabbitmq", path: "roles"}:                                                 {prefix: "RabbitMQ", suffix: "Roles"},
	{mount: "rabbitmq", path: "roles/{name}"}:                                          {prefix: "RabbitMQ", suffix: "Role"},
	{mount: "secret", path: "config"}:                                                  {prefix: "KVv2", suffix: "Config"},
	{mount: "secret", path: "data/{path}"}:                                             {prefix: "KVv2"},
	{mount: "secret", path: "delete/{path}"}:                                           {prefix: "KVv2", suffix: "Versions", operation: "Delete"},
	{mount: "secret", path: "destroy/{path}"}:                                          {prefix: "KVv2", suffix: "Versions", operation: "Destroy"},
	{mount: "secret", path: "metadata/{path}"}:                                         {prefix: "KVv2", suffix: "Metadata"},
	{mount: "secret", path: "subkeys/{path}"}:                                          {prefix: "KVv2", suffix: "Subkeys"},
	{mount: "secret", path: "undelete/{path}"}:                                         {prefix: "KVv2", suffix: "Versions", operation: "Undelete"},
	{mount: "ssh", path: "config/ca"}:                                                  {prefix: "SSH", suffix: "CAConfig"},
	{mount: "ssh", path: "config/zeroaddress"}:                                         {prefix: "SSH", suffix: "ZeroAddressConfig"},
	{mount: "ssh", path: "creds/{role}"}:                                               {prefix: "SSH", suffix: "Credentials"},
	{mount: "ssh", path: "issue/{role}"}:                                               {prefix: "SSH", suffix: "Issue"},
	{mount: "ssh", path: "keys/{key_name}"}:                                            {prefix: "SSH", suffix: "Keys"},
	{mount: "ssh", path: "lookup"}:                                                     {prefix: "SSH", operation: "Lookup"},
	{mount: "ssh", path: "public_key"}:                                                 {prefix: "SSH", suffix: "PublicKey"},
	{mount: "ssh", path: "roles"}:                                                      {prefix: "SSH", suffix: "Roles"},
	{mount: "ssh", path: "roles/{role}"}:                                               {prefix: "SSH", suffix: "Role"},
	{mount: "ssh", path: "sign/{role}"}:                                                {prefix: "SSH", operation: "Sign"},
	{mount: "ssh", path: "verify"}:                                                     {prefix: "SSH", operation: "Verify"},
	{mount: "sys", path: "audit"}:                                                      {suffix: "AuditDevices"},
	{mount: "sys", path: "audit/{path}"}:                                               {suffix: "AuditDevice"},
	{mount: "sys", path: "audit-hash/{path}"}:                                          {suffix: "AuditHash", operation: "Calculate"},
	{mount: "sys", path: "auth"}:                                                       {suffix: "AuthMethods"},
	{mount: "sys", path: "auth/{path}"}:                                                {suffix: "AuthMethod"},
	{mount: "sys", path: "auth/{path}/tune"}:                                           {suffix: "AuthMethodTune"},
	{mount: "sys", path: "capabilities"}:                                               {suffix: "Capabilities"},
	{mount: "sys", path: "capabilities-accessor"}:                                      {suffix: "CapabilitiesAccessor"},
	{mount: "sys", path: "capabilities-self"}:                                          {suffix: "CapabilitiesSelf"},
	{mount: "sys", path: "config/auditing/request-headers"}:                            {suffix: "ConfigAuditingRequestHeaders"},
	{mount: "sys", path: "config/auditing/request-headers/{header}"}:                   {suffix: "ConfigAuditingRequestHeader"},
	{mount: "sys", path: "config/cors"}:                                                {suffix: "ConfigCORS"},
	{mount: "sys", path: "config/reload/{subsystem}"}:                                  {suffix: "ConfigReloadSubsystem"},
	{mount: "sys", path: "config/state/sanitized"}:                                     {suffix: "ConfigStateSanitized"},
	{mount: "sys", path: "config/ui/headers/"}:                                         {suffix: "ConfigUIHeaders"},
	{mount: "sys", path: "config/ui/headers/{header}"}:                                 {suffix: "ConfigUIHeader"},
	{mount: "sys", path: "generate-root"}:                                              {suffix: "GenerateRoot"},
	{mount: "sys", path: "generate-root/attempt"}:                                      {suffix: "GenerateRootAttempt"},
	{mount: "sys", path: "generate-root/update"}:                                       {suffix: "GenerateRootUpdate"},
	{mount: "sys", path: "ha-status"}:                                                  {suffix: "HAStatus"},
	{mount: "sys", path: "health"}:                                                     {suffix: "Health"},
	{mount: "sys", path: "host-info"}:                                                  {suffix: "HostInfo"},
	{mount: "sys", path: "in-flight-req"}:                                              {suffix: "InFlightRequests"},
	{mount: "sys", path: "init"}:                                                       {suffix: "Init"},
	{mount: "sys", path: "internal/counters/activity"}:                                 {suffix: "InternalCountersActivity"},
	{mount: "sys", path: "internal/counters/activity/export"}:                          {suffix: "InternalCountersActivityExport"},
	{mount: "sys", path: "internal/counters/activity/monthly"}:                         {suffix: "InternalCountersActivityMonthly"},
	{mount: "sys", path: "internal/counters/config"}:                                   {suffix: "InternalCountersConfig"},
	{mount: "sys", path: "internal/counters/entities"}:                                 {suffix: "InternalCountersEntities"},
	{mount: "sys", path: "internal/counters/requests"}:                                 {suffix: "InternalCountersRequests"},
	{mount: "sys", path: "internal/counters/tokens"}:                                   {suffix: "InternalCountersTokens"},
	{mount: "sys", path: "internal/inspect/router/{tag}"}:                              {suffix: "InternalInspectRouter"},
	{mount: "sys", path: "internal/specs/openapi"}:                                     {suffix: "InternalSpecsOpenAPI"},
	{mount: "sys", path: "internal/ui/feature-flags"}:                                  {suffix: "InternalUIFeatureFlags"},
	{mount: "sys", path: "internal/ui/mounts"}:                                         {suffix: "InternalUIMounts"},
	{mount: "sys", path: "internal/ui/mounts/{path}"}:                                  {suffix: "InternalUIMount"},
	{mount: "sys", path: "internal/ui/namespaces"}:                                     {suffix: "InternalUINamespaces"},
	{mount: "sys", path: "internal/ui/resultant-acl"}:                                  {suffix: "InternalUIResultantACL"},
	{mount: "sys", path: "key-status"}:                                                 {suffix: "KeyStatus"},
	{mount: "sys", path: "leader"}:                                                     {suffix: "Leader"},
	{mount: "sys", path: "leases"}:                                                     {suffix: "Leases"},
	{mount: "sys", path: "leases/count"}:                                               {suffix: "LeasesCount"},
	{mount: "sys", path: "leases/lookup"}:                                              {suffix: "LeasesLookup"},
	{mount: "sys", path: "leases/lookup/{prefix}"}:                                     {suffix: "LeasesLookupPrefix"},
	{mount: "sys", path: "leases/renew"}:                                               {suffix: "LeasesRenew"},
	{mount: "sys", path: "leases/renew/{url_lease_id}"}:                                {suffix: "LeasesRenew2"},
	{mount: "sys", path: "leases/revoke"}:                                              {suffix: "LeasesRevoke"},
	{mount: "sys", path: "leases/revoke-force/{prefix}"}:                               {suffix: "LeasesRevokeForce"},
	{mount: "sys", path: "leases/revoke-prefix/{prefix}"}:                              {suffix: "LeasesRevokePrefix"},
	{mount: "sys", path: "leases/revoke/{url_lease_id}"}:                               {suffix: "LeasesRevoke2"},
	{mount: "sys", path: "leases/tidy"}:                                                {suffix: "LeasesTidy"},
	{mount: "sys", path: "loggers"}:                                                    {suffix: "Loggers"},
	{mount: "sys", path: "loggers/{name}"}:                                             {suffix: "Logger"},
	{mount: "sys", path: "metrics"}:                                                    {suffix: "Metrics"},
	{mount: "sys", path: "mfa/validate"}:                                               {prefix: "MFA", operation: "Validate"},
	{mount: "sys", path: "monitor"}:                                                    {operation: "Monitor"},
	{mount: "sys", path: "mounts"}:                                                     {suffix: "Mounts"},
	{mount: "sys", path: "mounts/{path}"}:                                              {suffix: "Mount"},
	{mount: "sys", path: "mounts/{path}/tune"}:                                         {suffix: "MountsConfig"},
	{mount: "sys", path: "plugins/catalog"}:                                            {suffix: "PluginsCatalog"},
	{mount: "sys", path: "plugins/catalog/{type}"}:                                     {suffix: "PluginsCatalogByType"},
	{mount: "sys", path: "plugins/catalog/{type}/{name}"}:                              {suffix: "PluginsCatalogByTypeByName"},
	{mount: "sys", path: "plugins/reload/backend"}:                                     {suffix: "PluginsReloadBackend"},
	{mount: "sys", path: "policies/acl"}:                                               {suffix: "PoliciesACL"},
	{mount: "sys", path: "policies/acl/{name}"}:                                        {suffix: "PoliciesACL"},
	{mount: "sys", path: "policies/password"}:                                          {suffix: "PoliciesPassword"},
	{mount: "sys", path: "policies/password/{name}"}:                                   {suffix: "PoliciesPassword"},
	{mount: "sys", path: "policies/password/{name}/generate"}:                          {suffix: "PoliciesPasswordGenerate"},
	{mount: "sys", path: "policy"}:                                                     {suffix: "Policies"},
	{mount: "sys", path: "policy/{name}"}:                                              {suffix: "Policy"},
	{mount: "sys", path: "pprof/"}:                                                     {prefix: "Pprof"},
	{mount: "sys", path: "pprof/allocs"}:                                               {prefix: "Pprof", suffix: "Allocs"},
	{mount: "sys", path: "pprof/block"}:                                                {prefix: "Pprof", suffix: "Block"},
	{mount: "sys", path: "pprof/cmdline"}:                                              {prefix: "Pprof", suffix: "Cmdline"},
	{mount: "sys", path: "pprof/goroutine"}:                                            {prefix: "Pprof", suffix: "Goroutine"},
	{mount: "sys", path: "pprof/heap"}:                                                 {prefix: "Pprof", suffix: "Heap"},
	{mount: "sys", path: "pprof/mutex"}:                                                {prefix: "Pprof", suffix: "Mutex"},
	{mount: "sys", path: "pprof/profile"}:                                              {prefix: "Pprof", suffix: "Profile"},
	{mount: "sys", path: "pprof/symbol"}:                                               {prefix: "Pprof", suffix: "Symbol"},
	{mount: "sys", path: "pprof/threadcreate"}:                                         {prefix: "Pprof", suffix: "Threadcreate"},
	{mount: "sys", path: "pprof/trace"}:                                                {prefix: "Pprof", suffix: "Trace"},
	{mount: "sys", path: "quotas/config"}:                                              {suffix: "QuotasConfig"},
	{mount: "sys", path: "quotas/rate-limit"}:                                          {suffix: "QuotasRateLimits"},
	{mount: "sys", path: "quotas/rate-limit/{name}"}:                                   {suffix: "QuotasRateLimit"},
	{mount: "sys", path: "raw"}:                                                        {suffix: "Raw"},
	{mount: "sys", path: "raw/{path}"}:                                                 {suffix: "RawPath"},
	{mount: "sys", path: "rekey/backup"}:                                               {suffix: "RekeyBackup"},
	{mount: "sys", path: "rekey/init"}:                                                 {suffix: "RekeyInit"},
	{mount: "sys", path: "rekey/recovery-key-backup"}:                                  {suffix: "RekeyRecoveryKeyBackup"},
	{mount: "sys", path: "rekey/update"}:                                               {suffix: "RekeyUpdate"},
	{mount: "sys", path: "rekey/verify"}:                                               {suffix: "RekeyVerify"},
	{mount: "sys", path: "remount"}:                                                    {operation: "Remount"},
	{mount: "sys", path: "remount/status/{migration_id}"}:                              {suffix: "RemountStatus"},
	{mount: "sys", path: "renew"}:                                                      {operation: "Renew"},
	{mount: "sys", path: "renew/{url_lease_id}"}:                                       {operation: "RenewFor"},
	{mount: "sys", path: "replication/status"}:                                         {suffix: "ReplicationStatus"},
	{mount: "sys", path: "revoke"}:                                                     {operation: "Revoke"},
	{mount: "sys", path: "revoke-force/{prefix}"}:                                      {operation: "RevokeForce"},
	{mount: "sys", path: "revoke-prefix/{prefix}"}:                                     {operation: "RevokePrefix"},
	{mount: "sys", path: "revoke/{url_lease_id}"}:                                      {operation: "RevokeLease"},
	{mount: "sys", path: "rotate"}:                                                     {operation: "Rotate"},
	{mount: "sys", path: "rotate/config"}:                                              {suffix: "RotateConfig"},
	{mount: "sys", path: "seal"}:                                                       {operation: "Seal"},
	{mount: "sys", path: "seal-status"}:                                                {suffix: "SealStatus"},
	{mount: "sys", path: "step-down"}:                                                  {operation: "StepDown", suffix: "Leader"},
	{mount: "sys", path: "tools/hash"}:                                                 {prefix: "Tools", operation: "Hash"},
	{mount: "sys", path: "tools/hash/{urlalgorithm}"}:                                  {prefix: "Tools", operation: "Hash", suffix: "With"},
	{mount: "sys", path: "tools/random"}:                                               {prefix: "Tools", operation: "Generate", suffix: "Random"},
	{mount: "sys", path: "tools/random/{source}"}:                                      {prefix: "Tools", operation: "Generate", suffix: "RandomSource"},
	{mount: "sys", path: "tools/random/{source}/{urlbytes}"}:                           {prefix: "Tools", operation: "Generate", suffix: "RandomSourceBytes"},
	{mount: "sys", path: "unseal"}:                                                     {operation: "Unseal"},
	{mount: "sys", path: "version-history/"}:                                           {suffix: "VersionHistory"},
	{mount: "sys", path: "wrapping/lookup"}:                                            {prefix: "Wrapping", suffix: "Lookup"},
	{mount: "sys", path: "wrapping/rewrap"}:                                            {prefix: "Wrapping", operation: "Rewrap"},
	{mount: "sys", path: "wrapping/unwrap"}:                                            {prefix: "Wrapping", operation: "Unwrap"},
	{mount: "sys", path: "wrapping/wrap"}:                                              {prefix: "Wrapping", operation: "Wrap"},
	{mount: "terraform", path: "config"}:                                               {prefix: "Terraform", suffix: "Config"},
	{mount: "terraform", path: "creds/{name}"}:                                         {prefix: "Terraform", suffix: "Credentials"},
	{mount: "terraform", path: "role"}:                                                 {prefix: "Terraform", suffix: "Roles"},
	{mount: "terraform", path: "role/{name}"}:                                          {prefix: "Terraform", suffix: "Role"},
	{mount: "terraform", path: "rotate-role/{name}"}:                                   {prefix: "Terraform", suffix: "Role", operation: "Rotate"},
	{mount: "totp", path: "code/{name}"}:                                               {prefix: "TOTP", suffix: "Code"},
	{mount: "totp", path: "keys"}:                                                      {prefix: "TOTP", suffix: "Keys"},
	{mount: "totp", path: "keys/{name}"}:                                               {prefix: "TOTP", suffix: "Key"},
	{mount: "transit", path: "backup/{name}"}:                                          {prefix: "Transit", operation: "Backup"},
	{mount: "transit", path: "cache-config"}:                                           {prefix: "Transit", suffix: "CacheConfig"},
	{mount: "transit", path: "datakey/{plaintext}/{name}"}:                             {prefix: "Transit", operation: "Generate", suffix: "DataKey"},
	{mount: "transit", path: "decrypt/{name}"}:                                         {prefix: "Transit", operation: "Decrypt"},
	{mount: "transit", path: "encrypt/{name}"}:                                         {prefix: "Transit", operation: "Encrypt"},
	{mount: "transit", path: "export/{type}/{name}"}:                                   {prefix: "Transit", operation: "Export"},
	{mount: "transit", path: "export/{type}/{name}/{version}"}:                         {prefix: "Transit", operation: "Export", suffix: "Version"},
	{mount: "transit", path: "hash"}:                                                   {prefix: "Transit", operation: "Hash"},
	{mount: "transit", path: "hash/{urlalgorithm}"}:                                    {prefix: "Transit", operation: "HashWithAlgorithm"},
	{mount: "transit", path: "hmac/{name}"}:                                            {prefix: "Transit", operation: "Generate", suffix: "HMAC"},
	{mount: "transit", path: "hmac/{name}/{urlalgorithm}"}:                             {prefix: "Transit", operation: "Generate", suffix: "HMACWithAlgorithm"},
	{mount: "transit", path: "keys"}:                                                   {prefix: "Transit", suffix: "Keys"},
	{mount: "transit", path: "keys/{name}"}:                                            {prefix: "Transit", suffix: "Key"},
	{mount: "transit", path: "keys/{name}/config"}:                                     {prefix: "Transit", suffix: "KeyConfig"},
	{mount: "transit", path: "keys/{name}/import"}:                                     {prefix: "Transit", suffix: "Key", operation: "Import"},
	{mount: "transit", path: "keys/{name}/import_version"}:                             {prefix: "Transit", suffix: "KeyVersion", operation: "Import"},
	{mount: "transit", path: "keys/{name}/rotate"}:                                     {prefix: "Transit", suffix: "Key", operation: "Rotate"},
	{mount: "transit", path: "keys/{name}/trim"}:                                       {prefix: "Transit", suffix: "Key", operation: "Trim"},
	{mount: "transit", path: "random"}:                                                 {prefix: "Transit", operation: "Generate", suffix: "Random"},
	{mount: "transit", path: "random/{source}"}:                                        {prefix: "Transit", operation: "Generate", suffix: "RandomSource"},
	{mount: "transit", path: "random/{source}/{urlbytes}"}:                             {prefix: "Transit", operation: "Generate", suffix: "RandomSourceBytes"},
	{mount: "transit", path: "restore"}:                                                {prefix: "Transit", operation: "Restore"},
	{mount: "transit", path: "restore/{name}"}:                                         {prefix: "Transit", operation: "Restore", suffix: "Key"},
	{mount: "transit", path: "rewrap/{name}"}:                                          {prefix: "Transit", operation: "Rewrap"},
	{mount: "transit", path: "sign/{name}"}:                                            {prefix: "Transit", operation: "Sign"},
	{mount: "transit", path: "sign/{name}/{urlalgorithm}"}:                             {prefix: "Transit", operation: "Sign", suffix: "WithAlgorithm"},
	{mount: "transit", path: "verify/{name}"}:                                          {prefix: "Transit", operation: "Verify"},
	{mount: "transit", path: "verify/{name}/{urlalgorithm}"}:                           {prefix: "Transit", operation: "Verify", suffix: "WithAlgorithm"},
	{mount: "transit", path: "wrapping_key"}:                                           {prefix: "Transit", suffix: "WrappingKey"},
}
