# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

version: "2"
linters:
  enable:
    - depguard
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - ./sdk/**
          allow:
            - github.com/hashicorp/go-metrics/compat
          deny:
            - pkg: github.com/hashicorp/go-metrics
              desc: not allowed, use github.com/hashicorp/go-metrics/compat instead
            - pkg: github.com/armon/go-metrics
              desc: not allowed, use github.com/hashicorp/go-metrics/compat instead
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
