name: vault
version: "0.6.2-dev"
summary: Vault is a tool for securely accessing secrets.
description: |
  A modern system requires access to a multitude of secrets: database
  credentials, API keys for external services, credentials for service-oriented
  architecture communication, etc. Understanding who is accessing what secrets
  is already very difficult and platform-specific. Adding on key rolling,
  secure storage, and detailed audit logs is almost impossible without a custom
  solution. This is where Vault steps in.
confinement: strict

apps:
  vault:
    command: bin/vault
    plugs: [network, network-bind]

parts:
  vault:
    source: .
    plugin: go
    go-importpath: github.com/hashicorp/vault
    go-buildtags: [vault]
    build-packages: [git, g++, libsasl2-dev]
