# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

---
name: Set up Go with a shared module cache.
description: Set up Go with a shared module cache.

inputs:
  github-token:
    description: An elevated Github token to access private HashiCorp modules.

runs:
  using: composite
  steps:
    - name: Set up pipeline
      shell: bash
      env:
        GOPRIVATE: github.com/hashicorp/*
      run: |
        git config --global url."https://${{ inputs.github-token }}@github.com".insteadOf https://github.com
        make tools-pipeline
