// Code generated by protoc-gen-go.
// source: builtin/logical/database/dbplugin/database.proto
// DO NOT EDIT!

/*
Package dbplugin is a generated protocol buffer package.

It is generated from these files:
	builtin/logical/database/dbplugin/database.proto

It has these top-level messages:
	InitializeRequest
	CreateUserRequest
	RenewUserRequest
	RevokeUserRequest
	RotateRootCredentialsRequest
	Statements
	UsernameConfig
	InitializeResponse
	CreateUserResponse
	TypeResponse
	RotateRootCredentialsResponse
	Empty
*/
package dbplugin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitializeRequest struct {
	Config           []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	VerifyConnection bool   `protobuf:"varint,2,opt,name=verify_connection,json=verifyConnection" json:"verify_connection,omitempty"`
}

func (m *InitializeRequest) Reset()                    { *m = InitializeRequest{} }
func (m *InitializeRequest) String() string            { return proto.CompactTextString(m) }
func (*InitializeRequest) ProtoMessage()               {}
func (*InitializeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InitializeRequest) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *InitializeRequest) GetVerifyConnection() bool {
	if m != nil {
		return m.VerifyConnection
	}
	return false
}

type CreateUserRequest struct {
	Statements     *Statements                `protobuf:"bytes,1,opt,name=statements" json:"statements,omitempty"`
	UsernameConfig *UsernameConfig            `protobuf:"bytes,2,opt,name=username_config,json=usernameConfig" json:"username_config,omitempty"`
	Expiration     *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=expiration" json:"expiration,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateUserRequest) GetStatements() *Statements {
	if m != nil {
		return m.Statements
	}
	return nil
}

func (m *CreateUserRequest) GetUsernameConfig() *UsernameConfig {
	if m != nil {
		return m.UsernameConfig
	}
	return nil
}

func (m *CreateUserRequest) GetExpiration() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type RenewUserRequest struct {
	Statements *Statements                `protobuf:"bytes,1,opt,name=statements" json:"statements,omitempty"`
	Username   string                     `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Expiration *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=expiration" json:"expiration,omitempty"`
}

func (m *RenewUserRequest) Reset()                    { *m = RenewUserRequest{} }
func (m *RenewUserRequest) String() string            { return proto.CompactTextString(m) }
func (*RenewUserRequest) ProtoMessage()               {}
func (*RenewUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RenewUserRequest) GetStatements() *Statements {
	if m != nil {
		return m.Statements
	}
	return nil
}

func (m *RenewUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RenewUserRequest) GetExpiration() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

type RevokeUserRequest struct {
	Statements *Statements `protobuf:"bytes,1,opt,name=statements" json:"statements,omitempty"`
	Username   string      `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *RevokeUserRequest) Reset()                    { *m = RevokeUserRequest{} }
func (m *RevokeUserRequest) String() string            { return proto.CompactTextString(m) }
func (*RevokeUserRequest) ProtoMessage()               {}
func (*RevokeUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RevokeUserRequest) GetStatements() *Statements {
	if m != nil {
		return m.Statements
	}
	return nil
}

func (m *RevokeUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RotateRootCredentialsRequest struct {
	Statements string `protobuf:"bytes,1,opt,name=statements" json:"statements,omitempty"`
	Config     []byte `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *RotateRootCredentialsRequest) Reset()                    { *m = RotateRootCredentialsRequest{} }
func (m *RotateRootCredentialsRequest) String() string            { return proto.CompactTextString(m) }
func (*RotateRootCredentialsRequest) ProtoMessage()               {}
func (*RotateRootCredentialsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RotateRootCredentialsRequest) GetStatements() string {
	if m != nil {
		return m.Statements
	}
	return ""
}

func (m *RotateRootCredentialsRequest) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type Statements struct {
	CreationStatements   string `protobuf:"bytes,1,opt,name=creation_statements,json=creationStatements" json:"creation_statements,omitempty"`
	RevocationStatements string `protobuf:"bytes,2,opt,name=revocation_statements,json=revocationStatements" json:"revocation_statements,omitempty"`
	RollbackStatements   string `protobuf:"bytes,3,opt,name=rollback_statements,json=rollbackStatements" json:"rollback_statements,omitempty"`
	RenewStatements      string `protobuf:"bytes,4,opt,name=renew_statements,json=renewStatements" json:"renew_statements,omitempty"`
}

func (m *Statements) Reset()                    { *m = Statements{} }
func (m *Statements) String() string            { return proto.CompactTextString(m) }
func (*Statements) ProtoMessage()               {}
func (*Statements) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Statements) GetCreationStatements() string {
	if m != nil {
		return m.CreationStatements
	}
	return ""
}

func (m *Statements) GetRevocationStatements() string {
	if m != nil {
		return m.RevocationStatements
	}
	return ""
}

func (m *Statements) GetRollbackStatements() string {
	if m != nil {
		return m.RollbackStatements
	}
	return ""
}

func (m *Statements) GetRenewStatements() string {
	if m != nil {
		return m.RenewStatements
	}
	return ""
}

type UsernameConfig struct {
	DisplayName string `protobuf:"bytes,1,opt,name=DisplayName" json:"DisplayName,omitempty"`
	RoleName    string `protobuf:"bytes,2,opt,name=RoleName" json:"RoleName,omitempty"`
}

func (m *UsernameConfig) Reset()                    { *m = UsernameConfig{} }
func (m *UsernameConfig) String() string            { return proto.CompactTextString(m) }
func (*UsernameConfig) ProtoMessage()               {}
func (*UsernameConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UsernameConfig) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UsernameConfig) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type InitializeResponse struct {
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *InitializeResponse) Reset()                    { *m = InitializeResponse{} }
func (m *InitializeResponse) String() string            { return proto.CompactTextString(m) }
func (*InitializeResponse) ProtoMessage()               {}
func (*InitializeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *InitializeResponse) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type CreateUserResponse struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type TypeResponse struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *TypeResponse) Reset()                    { *m = TypeResponse{} }
func (m *TypeResponse) String() string            { return proto.CompactTextString(m) }
func (*TypeResponse) ProtoMessage()               {}
func (*TypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TypeResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type RotateRootCredentialsResponse struct {
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *RotateRootCredentialsResponse) Reset()                    { *m = RotateRootCredentialsResponse{} }
func (m *RotateRootCredentialsResponse) String() string            { return proto.CompactTextString(m) }
func (*RotateRootCredentialsResponse) ProtoMessage()               {}
func (*RotateRootCredentialsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RotateRootCredentialsResponse) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*InitializeRequest)(nil), "dbplugin.InitializeRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "dbplugin.CreateUserRequest")
	proto.RegisterType((*RenewUserRequest)(nil), "dbplugin.RenewUserRequest")
	proto.RegisterType((*RevokeUserRequest)(nil), "dbplugin.RevokeUserRequest")
	proto.RegisterType((*RotateRootCredentialsRequest)(nil), "dbplugin.RotateRootCredentialsRequest")
	proto.RegisterType((*Statements)(nil), "dbplugin.Statements")
	proto.RegisterType((*UsernameConfig)(nil), "dbplugin.UsernameConfig")
	proto.RegisterType((*InitializeResponse)(nil), "dbplugin.InitializeResponse")
	proto.RegisterType((*CreateUserResponse)(nil), "dbplugin.CreateUserResponse")
	proto.RegisterType((*TypeResponse)(nil), "dbplugin.TypeResponse")
	proto.RegisterType((*RotateRootCredentialsResponse)(nil), "dbplugin.RotateRootCredentialsResponse")
	proto.RegisterType((*Empty)(nil), "dbplugin.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Database service

type DatabaseClient interface {
	Type(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TypeResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	RenewUser(ctx context.Context, in *RenewUserRequest, opts ...grpc.CallOption) (*Empty, error)
	RevokeUser(ctx context.Context, in *RevokeUserRequest, opts ...grpc.CallOption) (*Empty, error)
	RotateRootCredentials(ctx context.Context, in *RotateRootCredentialsRequest, opts ...grpc.CallOption) (*RotateRootCredentialsResponse, error)
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type databaseClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseClient(cc *grpc.ClientConn) DatabaseClient {
	return &databaseClient{cc}
}

func (c *databaseClient) Type(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TypeResponse, error) {
	out := new(TypeResponse)
	err := grpc.Invoke(ctx, "/dbplugin.Database/Type", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := grpc.Invoke(ctx, "/dbplugin.Database/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) RenewUser(ctx context.Context, in *RenewUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/dbplugin.Database/RenewUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) RevokeUser(ctx context.Context, in *RevokeUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/dbplugin.Database/RevokeUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) RotateRootCredentials(ctx context.Context, in *RotateRootCredentialsRequest, opts ...grpc.CallOption) (*RotateRootCredentialsResponse, error) {
	out := new(RotateRootCredentialsResponse)
	err := grpc.Invoke(ctx, "/dbplugin.Database/RotateRootCredentials", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	out := new(InitializeResponse)
	err := grpc.Invoke(ctx, "/dbplugin.Database/Initialize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/dbplugin.Database/Close", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Database service

type DatabaseServer interface {
	Type(context.Context, *Empty) (*TypeResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	RenewUser(context.Context, *RenewUserRequest) (*Empty, error)
	RevokeUser(context.Context, *RevokeUserRequest) (*Empty, error)
	RotateRootCredentials(context.Context, *RotateRootCredentialsRequest) (*RotateRootCredentialsResponse, error)
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	Close(context.Context, *Empty) (*Empty, error)
}

func RegisterDatabaseServer(s *grpc.Server, srv DatabaseServer) {
	s.RegisterService(&_Database_serviceDesc, srv)
}

func _Database_Type_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).Type(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbplugin.Database/Type",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).Type(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbplugin.Database/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_RenewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).RenewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbplugin.Database/RenewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).RenewUser(ctx, req.(*RenewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_RevokeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).RevokeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbplugin.Database/RevokeUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).RevokeUser(ctx, req.(*RevokeUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_RotateRootCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateRootCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).RotateRootCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbplugin.Database/RotateRootCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).RotateRootCredentials(ctx, req.(*RotateRootCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbplugin.Database/Initialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbplugin.Database/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).Close(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Database_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dbplugin.Database",
	HandlerType: (*DatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Type",
			Handler:    _Database_Type_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Database_CreateUser_Handler,
		},
		{
			MethodName: "RenewUser",
			Handler:    _Database_RenewUser_Handler,
		},
		{
			MethodName: "RevokeUser",
			Handler:    _Database_RevokeUser_Handler,
		},
		{
			MethodName: "RotateRootCredentials",
			Handler:    _Database_RotateRootCredentials_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _Database_Initialize_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Database_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "builtin/logical/database/dbplugin/database.proto",
}

func init() { proto.RegisterFile("builtin/logical/database/dbplugin/database.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5f, 0x4f, 0x13, 0x41,
	0x10, 0xcf, 0xf1, 0xcf, 0x32, 0x10, 0xa0, 0x2b, 0x10, 0x72, 0xa2, 0x92, 0x7b, 0x50, 0x88, 0xa6,
	0x67, 0xc0, 0x44, 0xe3, 0x9b, 0x29, 0xc6, 0x98, 0x18, 0x1e, 0x56, 0x30, 0xbe, 0x91, 0xed, 0x75,
	0xa8, 0x1b, 0xae, 0xbb, 0xe7, 0xed, 0x1e, 0x58, 0x3f, 0x8d, 0x1f, 0xc7, 0x27, 0x9f, 0xfd, 0x38,
	0xe6, 0xf6, 0x6e, 0xbb, 0xdb, 0x5e, 0x91, 0x07, 0xe2, 0x5b, 0x67, 0xe6, 0x37, 0x33, 0xbf, 0x99,
	0xfb, 0xcd, 0x16, 0x5e, 0xf4, 0x0a, 0x9e, 0x6a, 0x2e, 0xe2, 0x54, 0x0e, 0x78, 0xc2, 0xd2, 0xb8,
	0xcf, 0x34, 0xeb, 0x31, 0x85, 0x71, 0xbf, 0x97, 0xa5, 0xc5, 0x80, 0x8b, 0xb1, 0xa7, 0x93, 0xe5,
	0x52, 0x4b, 0xd2, 0xb2, 0x81, 0xf0, 0xf1, 0x40, 0xca, 0x41, 0x8a, 0xb1, 0xf1, 0xf7, 0x8a, 0x8b,
	0x58, 0xf3, 0x21, 0x2a, 0xcd, 0x86, 0x59, 0x05, 0x8d, 0xbe, 0x40, 0xfb, 0x83, 0xe0, 0x9a, 0xb3,
	0x94, 0xff, 0x40, 0x8a, 0xdf, 0x0a, 0x54, 0x9a, 0x6c, 0xc3, 0x52, 0x22, 0xc5, 0x05, 0x1f, 0xec,
	0x04, 0x7b, 0xc1, 0xfe, 0x2a, 0xad, 0x2d, 0xf2, 0x0c, 0xda, 0x57, 0x98, 0xf3, 0x8b, 0xd1, 0x79,
	0x22, 0x85, 0xc0, 0x44, 0x73, 0x29, 0x76, 0xe6, 0xf6, 0x82, 0xfd, 0x16, 0xdd, 0xa8, 0x02, 0xdd,
	0xb1, 0x3f, 0xfa, 0x15, 0x40, 0xbb, 0x9b, 0x23, 0xd3, 0x78, 0xa6, 0x30, 0xb7, 0xa5, 0x5f, 0x02,
	0x28, 0xcd, 0x34, 0x0e, 0x51, 0x68, 0x65, 0xca, 0xaf, 0x1c, 0x6e, 0x76, 0x2c, 0xdf, 0xce, 0xa7,
	0x71, 0x8c, 0x7a, 0x38, 0xf2, 0x16, 0xd6, 0x0b, 0x85, 0xb9, 0x60, 0x43, 0x3c, 0xaf, 0x99, 0xcd,
	0x99, 0xd4, 0x1d, 0x97, 0x7a, 0x56, 0x03, 0xba, 0x26, 0x4e, 0xd7, 0x8a, 0x09, 0x9b, 0xbc, 0x01,
	0xc0, 0xef, 0x19, 0xcf, 0x99, 0x21, 0x3d, 0x6f, 0xb2, 0xc3, 0x4e, 0xb5, 0x9e, 0x8e, 0x5d, 0x4f,
	0xe7, 0xd4, 0xae, 0x87, 0x7a, 0xe8, 0xe8, 0x67, 0x00, 0x1b, 0x14, 0x05, 0x5e, 0xdf, 0x7d, 0x92,
	0x10, 0x5a, 0x96, 0x98, 0x19, 0x61, 0x99, 0x8e, 0xed, 0x3b, 0x51, 0x44, 0x68, 0x53, 0xbc, 0x92,
	0x97, 0xf8, 0x5f, 0x29, 0x46, 0x9f, 0x61, 0x97, 0xca, 0x12, 0x4a, 0xa5, 0xd4, 0xdd, 0x1c, 0xfb,
	0x28, 0x4a, 0xed, 0x28, 0xdb, 0xf1, 0x51, 0xa3, 0xe3, 0xf2, 0x44, 0x6d, 0xa7, 0xac, 0x39, 0x5f,
	0x59, 0xd1, 0xef, 0x00, 0xc0, 0xd1, 0x21, 0x31, 0xdc, 0x4f, 0x4a, 0xe9, 0x70, 0x29, 0xce, 0x1b,
	0xf5, 0x88, 0x0d, 0x79, 0x09, 0x47, 0xb0, 0x95, 0xe3, 0x95, 0x4c, 0x1a, 0x29, 0xd5, 0x00, 0x9b,
	0x2e, 0x38, 0xd9, 0x25, 0x97, 0x69, 0xda, 0x63, 0xc9, 0xa5, 0x9f, 0x32, 0x5f, 0x75, 0xb1, 0x21,
	0x2f, 0xe1, 0x00, 0x36, 0xf2, 0x52, 0x06, 0x3e, 0x7a, 0xc1, 0xa0, 0xd7, 0x8d, 0xdf, 0x41, 0xa3,
	0x13, 0x58, 0x9b, 0x14, 0x24, 0xd9, 0x83, 0x95, 0x63, 0xae, 0xb2, 0x94, 0x8d, 0x4e, 0xca, 0xcd,
	0x56, 0xb3, 0xf8, 0xae, 0x72, 0xf1, 0x54, 0xa6, 0x78, 0xe2, 0x2d, 0xde, 0xda, 0xd1, 0x73, 0x20,
	0xfe, 0x9d, 0xaa, 0x4c, 0x0a, 0x85, 0x37, 0x1d, 0x6a, 0xf4, 0x11, 0x88, 0x7f, 0x7a, 0x35, 0xda,
	0xff, 0xb0, 0xc1, 0x94, 0xf6, 0x42, 0x68, 0x65, 0x4c, 0xa9, 0x6b, 0x99, 0xf7, 0x6d, 0x6f, 0x6b,
	0x47, 0x11, 0xac, 0x9e, 0x8e, 0x32, 0xd7, 0x95, 0xc0, 0x82, 0x1e, 0x65, 0xb6, 0x86, 0xf9, 0x1d,
	0xbd, 0x82, 0x87, 0x37, 0x08, 0xe3, 0x16, 0xaa, 0xf7, 0x60, 0xf1, 0xdd, 0x30, 0xd3, 0xa3, 0xc3,
	0x3f, 0xf3, 0xd0, 0x3a, 0xae, 0xdf, 0x31, 0x12, 0xc3, 0x42, 0xd9, 0x92, 0xac, 0x3b, 0xb5, 0x1a,
	0x54, 0xb8, 0xed, 0x1c, 0x13, 0x9c, 0xde, 0x03, 0xb8, 0x89, 0xc9, 0x03, 0x87, 0x6a, 0x3c, 0x41,
	0xe1, 0xee, 0xec, 0x60, 0x5d, 0xe8, 0x35, 0x2c, 0x8f, 0x4f, 0x9d, 0x84, 0x0e, 0x3a, 0x7d, 0xff,
	0xe1, 0x34, 0xb5, 0xf2, 0x7c, 0xdd, 0x09, 0xfa, 0x14, 0x1a, 0x87, 0xd9, 0xcc, 0xfd, 0x0a, 0x5b,
	0x33, 0xd7, 0x47, 0x9e, 0x78, 0x65, 0xfe, 0x71, 0x78, 0xe1, 0xd3, 0x5b, 0x71, 0x6e, 0x51, 0x4e,
	0x48, 0x3e, 0xcb, 0xc6, 0xdf, 0x80, 0xbf, 0xa8, 0x19, 0xda, 0x3b, 0x80, 0xc5, 0x6e, 0x2a, 0xd5,
	0x8c, 0x6f, 0x34, 0xed, 0xe8, 0x2d, 0x99, 0xc7, 0xeb, 0xe8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xcb, 0x78, 0x4c, 0x8e, 0xca, 0x06, 0x00, 0x00,
}
