// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: BUSL-1.1

//go:build !enterprise && !minimal

package command

import (
	"maps"
	"testing"

	"github.com/stretchr/testify/require"
)

// Test_extendFullAddonCommands tests extendFullAddonCommands() extends physical and logical backends with
// full addon physical and logical backends generated by newFullAddonCommands()
func Test_extendFullAddonCommands(t *testing.T) {
	expMinPhysicalBackends := maps.Clone(physicalBackends)
	expMinLoginHandlers := maps.Clone(loginHandlers)

	expAddonPhysicalBackends, expAddonLogicalHandlers := newFullAddonCommands()

	extendFullAddonCommands()

	require.Equal(t, len(expMinPhysicalBackends)+len(expAddonPhysicalBackends), len(physicalBackends),
		"extended total physical backends mismatch total of minimal and full addon physical backends")
	require.Equal(t, len(expMinLoginHandlers)+len(expAddonLogicalHandlers), len(loginHandlers),
		"extended total logical handlers mismatch total of minimal and full addon logical handlers")

	for k := range expMinPhysicalBackends {
		require.Contains(t, physicalBackends, k, "expected to contain minimal physical backend")
	}

	for k := range expAddonPhysicalBackends {
		require.Contains(t, physicalBackends, k, "expected to contain full addon physical backend")
	}

	for k := range expMinLoginHandlers {
		require.Contains(t, loginHandlers, k, "expected to contain minimal login handler")
	}

	for k := range expAddonLogicalHandlers {
		require.Contains(t, loginHandlers, k, "expected to contain full addon login handler")
	}
}
