{
 "title": "Vault Writes",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vault HTTP req/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(vault_core_handle_request_count[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Vault HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(vault_core_handle_request) by (quantile)",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "avg( irate(vault_core_handle_request_sum[5m])/irate(vault_core_handle_request_count[5m])) by (instance)",
     "legendFormat": "{{instance}} mean"
    }
   ]
  },
  { "title": "Vault Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg by(instance, mode) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"vault-.*\"}[5m]))",
     "legendFormat": "{{instance}} CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"vault-.*\"} - node_memory_MemFree_bytes{instance=~\"vault-.*\"} - node_memory_Buffers_bytes{instance=~\"vault-.*\"} - node_memory_Cached_bytes{instance=~\"vault-.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Flushes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(node_disk_flush_requests_total{device=\"xvda\", instance=~\"vault-.*\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Ops/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"xvda\", instance=~\"vault-.*\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"xvda\", instance=~\"vault-.*\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"xvda\", instance=~\"vault-.*\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Client Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg by(instance, mode) (irate(node_cpu_seconds_total{mode=\"idle\", instance=\"k6\"}[5m]))",
     "legendFormat": "{{instance}} CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"k6\"} - node_memory_MemFree_bytes{instance=\"k6\"} - node_memory_Buffers_bytes{instance=\"k6\"} - node_memory_Cached_bytes{instance=\"k6\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Raft Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Raft Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_raft_commitTime", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_raft_commitTime_sum[5m])/irate(vault_raft_commitTime_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Raft Storage Transaction Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_raft_storage_transaction", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_raft_storage_transaction_sum[5m])/irate(vault_raft_storage_transaction_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Raft Store Logs Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(vault_raft_rpc_appendEntries_storeLogs_sum[5m])/irate(vault_raft_rpc_appendEntries_storeLogs_count[5m])",
     "legendFormat": "Follower Store Logs {{instance}} mean"
    },
    {
     "expr": "irate(vault_raft_leader_dispatchLog_sum[5m])/irate(vault_raft_leader_dispatchLog_count[5m])",
     "legendFormat": "Leader Dispatch Logs mean"
    }
   ]
  },
  { "title": "WAL Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "WAL Persist Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_wal_persistWALs", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_wal_persistWALs_sum[5m])/irate(vault_wal_persistWALs_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "WAL Flush/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(vault_wal_persistWALs_count[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAL Flush Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "vault_wal_flushReady", "legendFormat": "{{quantile}}" },
    {
     "expr": "irate(vault_wal_flushReady_sum[5m])/irate(vault_wal_flushReady_count[5m])",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "WAL Writes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "irate(vault_wal_flushReady_count{}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "FSM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "FSM Apply Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(vault_raft_fsm_applyBatch_sum[5m])/irate(vault_raft_fsm_applyBatch_count[5m])",
     "legendFormat": "{{instance}} mean"
    }
   ]
  }
 ]
}