#!/bin/bash

set -eu

USER="vault"

if ! id -u $USER > /dev/null 2>&1; then
	if command -v useradd &> /dev/null; then
		useradd \
			--system \
			--user-group \
			--shell /bin/false \
			$USER
	fi
fi
