/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: BUSL-1.1
 */

import Route from '@ember/routing/route';
import { service } from '@ember/service';

const mockPlugins = [
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'AUTH',
    pluginVersion: '0.0.0',
    externalUrl: 'https://mammoth-studio.info/',
    description:
      'Provides an automated mechanism to retrieve a Vault token for IAM principals and AWS EC2 instances.',
    author: 'hashicorp',
    pluginName: 'AWS Auth Method',
    id: '187d0660-e5a3-42bb-8d81-5faa5c7026d3',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'SECRET',
    pluginVersion: '0.0.0',
    externalUrl: 'https://complete-publishing.info/',
    description: 'Generate AWS access credentials dynamically based on IAM policies.',
    author: 'hashicorp',
    pluginName: 'AWS Secrets Engine',
    id: '6b85f2b2-6cdd-4e21-877c-7160820a4dd7',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'SECRET',
    pluginVersion: '0.0.0',
    externalUrl: 'https://meager-swath.com/',
    description: 'Manages passwords for Active Directory accounts.',
    author: 'hashicorp',
    pluginName: 'Active Directory Secrets Engine',
    id: '2ed96f66-15b4-4770-aa86-9d4e9b11c2f6',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'AUTH',
    pluginVersion: '0.0.0',
    externalUrl: 'https://ashamed-revenue.name/',
    description: 'Allows authentication to Vault using Resource Access Management (RAM).',
    author: 'hashicorp',
    pluginName: 'AliCloud Auth Method',
    id: 'c3aa0777-2fcd-4b89-850d-966f9ddcb517',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'SECRET',
    pluginVersion: '0.0.0',
    externalUrl: 'https://unwelcome-sepal.net/',
    description: 'Dynamic secrets for Alibaba Cloud.',
    author: 'hashicorp',
    pluginName: 'AliCloud Secrets Engine',
    id: '28151fe4-ecd4-46cb-9e4f-08d85af703ba',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'AUTH',
    pluginVersion: '0.0.0',
    externalUrl: 'https://hoarse-councilor.name/',
    description: 'Allows machines or apps to authenticate with Vault-defined roles.',
    author: 'hashicorp',
    pluginName: 'AppRole Auth Method',
    id: '298ae647-eafa-4178-a889-52b0d4757625',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'AUTH',
    pluginVersion: '0.0.0',
    externalUrl: 'https://frightening-designation.name',
    description: 'Allows authentication against Vault using Azure Active Directory credentials.',
    author: 'hashicorp',
    pluginName: 'Azure Auth Method',
    id: '658f6ece-2555-458e-b8df-7290622c903c',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'SECRET',
    pluginVersion: '0.0.0',
    externalUrl: 'https://sardonic-glove.com',
    description: 'Dynamically generate Azure service principals along with role and group assignments.',
    author: 'hashicorp',
    pluginName: 'Azure Secrets Engine',
    id: 'e9ef90c9-71e7-47c0-9637-89231efe7ffb',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'DATABASE',
    pluginVersion: '0.0.0',
    externalUrl: 'https://minty-guava.biz/',
    description:
      'Generates database credentials dynamically based on configured roles for a Cassandra database.',
    author: 'hashicorp',
    pluginName: 'Cassandra Database Secrets Engine',
    id: '71282bd9-a519-4cc1-b109-116638a31caf',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'AUTH',
    pluginVersion: '0.0.0',
    externalUrl: 'https://spry-volunteering.org',
    description: 'Allows for Centrify Identity Platform users accounts to authenticate with Vault.',
    author: 'hashicorp',
    pluginName: 'Centrify Auth Method',
    id: 'fb35ef25-126c-4f20-9da8-0cd11b117022',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'AUTH',
    pluginVersion: '0.0.0',
    externalUrl: 'https://old-fashioned-parable.biz/',
    description:
      "Leverages Cloud Foundry's App and Container Identity Assurance for authenticating to Vault.",
    author: 'hashicorp',
    pluginName: 'Cloud Foundry Auth Method',
    id: 'ad694e16-d17b-4b6c-ae45-1d10ee857d86',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'SECRET',
    pluginVersion: '0.0.0',
    externalUrl: 'https://wordy-passport.info/',
    description: 'Generate Consul API tokens dynamically based on Consul ACL policies.',
    author: 'hashicorp',
    pluginName: 'Consul Secrets Engine',
    id: '977d3c03-9b15-4ee7-97a1-e7f7e09d355f',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'DATABASE',
    pluginVersion: '0.0.0',
    externalUrl: 'https://optimal-compassionate.org',
    description:
      'Generates database credentials dynamically based on configured roles for a Couchbase database.',
    author: 'hashicorp',
    pluginName: 'Couchbase Database Secrets Engine',
    id: '435af914-5a64-4c0c-ae38-f4b6b56e926a',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'DATABASE',
    pluginVersion: '0.0.0',
    externalUrl: 'https://sniveling-tram.info/',
    description:
      'Provides short-lived credentials for Elasticsearch that are unique to each user or application.',
    author: 'hashicorp',
    pluginName: 'Elasticsearch Database Secrets Engine',
    id: 'f48d88d9-6833-40a0-ad80-2f713aab1e46',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'AUTH',
    pluginVersion: '0.0.0',
    externalUrl: 'https://noted-linen.com',
    description: 'Authenticate with Vault using a GitHub personal access token.',
    author: 'hashicorp',
    pluginName: 'GitHub Auth Method',
    id: '49af9a18-0bfd-4fe4-a91e-ffe8c1edad82',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'AUTH',
    pluginVersion: '0.0.0',
    externalUrl: 'https://noted-bankruptcy.com',
    description: 'Allows for various Google Cloud entities to authenticate with Vault.',
    author: 'hashicorp',
    pluginName: 'Google Cloud Auth Method',
    id: 'aa87bf46-66b8-4e16-9aba-981b64a36398',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'SECRET',
    pluginVersion: '0.0.0',
    externalUrl: 'https://tempting-recovery.org/',
    description: 'Encryption and key management via Google Cloud KMS.',
    author: 'hashicorp',
    pluginName: 'Google Cloud KMS Secrets Engine',
    id: '1caca547-7e77-487a-9de5-cd4bfa014625',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'SECRET',
    pluginVersion: '0.0.0',
    externalUrl: 'https://enormous-syndicate.org',
    description:
      'Dynamically generate Google Cloud service account keys and OAuth tokens based on IAM policies.',
    author: 'hashicorp',
    pluginName: 'Google Cloud Secrets Engine',
    id: '452f3d87-832e-4309-b2ee-dab1e65dc1c1',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'DATABASE',
    pluginVersion: '0.0.0',
    externalUrl: 'https://profuse-intelligence.net/',
    description: 'Generate database credentials dynamically based on configured roles for a HANA database.',
    author: 'hashicorp',
    pluginName: 'HanaDB Database Secrets Engine',
    id: '4aa12904-b33a-441a-857e-4dcdaa444431',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'DATABASE',
    pluginVersion: '0.0.0',
    externalUrl: 'https://damaged-jury.info',
    description:
      'Generate database credentials dynamically based on configured roles for an InfluxDB database.',
    author: 'hashicorp',
    pluginName: 'InfluxDB Database Secrets Engine',
    id: '7f2b350e-166e-4e82-86ac-cb937413d853',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'AUTH',
    pluginVersion: '0.0.0',
    externalUrl: 'https://delicious-god.net/',
    description: 'Allows for JWTs (including OIDC tokens) to authenticate with Vault.',
    author: 'hashicorp',
    pluginName: 'JWT Auth Method',
    id: '872f2489-f912-4112-9854-56061e231a2c',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'enterprise', 'official'],
    pluginType: 'SECRET',
    pluginVersion: '0.0.0',
    externalUrl: 'https://putrid-reamer.info/',
    description:
      'Allows Vault to act as a Key Management Interoperability Protocol (KMIP) server provider and handle the lifecycle of its KMIP managed objects.',
    author: 'hashicorp',
    pluginName: 'KMIP Secrets Engine',
    id: '2a2012a0-f9a4-4dd9-9a70-f03673b272de',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'SECRET',
    pluginVersion: '0.0.0',
    externalUrl: 'https://normal-type.org',
    description:
      'A generic Key-Value store used to store arbitrary secrets within the configured physical storage for Vault.',
    author: 'hashicorp',
    pluginName: 'KV Secrets Engine',
    id: 'e8072e75-462b-473e-9570-745f7b17e47b',
  },
  {
    publishDate: new Date(),
    official: { author: 'hashicorp', tags: 'official' },
    tags: ['built-in', 'official'],
    pluginType: 'AUTH',
    pluginVersion: '0.0.0',
    externalUrl: 'https://rusty-oboe.net/',
    description: 'Allows for users to authenticate with Vault via Kerberos/SPNEGO.',
    author: 'hashicorp',
    pluginName: 'Kerberos Auth Method',
    id: '5f0cc165-8649-4b07-832f-d375e67f710c',
  },
];
export default class MessagesRoute extends Route {
  @service pagination;

  model() {
    return mockPlugins;
  }
}
