#!/bin/sh

remote="$1"

if [ "$remote" = "enterprise" ]; then
    exit 0
fi

if [ "$remote" = "ent" ]; then
    exit 0
fi

if [ -f version/version_ent.go ]; then
    echo "Found enterprise version file while pushing to oss remote"
    exit 1
fi

exit 0
