#!/usr/bin/env bash

MIN_CIRCLECI_VERSION=0.1.5575

# Check .circleci/config.yml is up to date and valid, and that all changes are
# included together in this commit.
circleci_verify() {

  # Fail early if we accidentally used '.yaml' instead of '.yml'
  if ! git diff --name-only --cached --exit-code -- '.circleci/***.yaml'; then
    # This is just for consistency, as I keep making this mistake - Sam.
    block "ERROR: File(s) with .yaml extension detected. Please rename them .yml instead."
  fi

  # Succeed early if no changes to yml files in .circleci/ are currently staged.
  # make ci-verify is slow so we really don't want to run it unnecessarily.
  if git diff --name-only --cached --exit-code -- '.circleci/***.yml'; then
    return 0
  fi
  # Make sure to add no explicit output before this line, as it would just be noise
  # for those making non-circleci changes.
  echo "==> Verifying config changes in .circleci/"
  echo "--> OK: All files are .yml not .yaml"

  # Ensure commit includes _all_ files in .circleci/
  # So not only are the files up to date, but we are also committing them in one go.
  if ! git diff --name-only --exit-code -- '.circleci/***.yml'; then
    echo "ERROR: Some .yml diffs in .circleci/ are staged, others not."
    block "Please commit the entire .circleci/ directory together, or omit it altogether."
  fi

  echo "--> OK: All .yml files in .circleci are staged."

  if ! REASON=$(check_circleci_cli_version); then
    echo "*** WARNING: Unable to verify changes in .circleci/:"
    echo "--> $REASON"
    # We let this pass if there is no valid circleci version installed.
    return 0
  fi

  if ! make -C .circleci ci-verify; then
    block "ERROR: make ci-verify failed"
  fi

  echo "--> OK: make ci-verify succeeded."
}

check_circleci_cli_version() {
  if ! command -v circleci > /dev/null 2>&1; then
    echo "circleci cli not installed." 
    return 1
  fi

  CCI="circleci --skip-update-check"

  if ! THIS_VERSION=$($CCI version) > /dev/null 2>&1; then
    # Guards against very old versions that do not have --skip-update-check.
    echo "The installed circleci cli is too old. Please upgrade to at least $MIN_CIRCLECI_VERSION." 
    return 1
  fi

  # SORTED_MIN is the lower of the THIS_VERSION and MIN_CIRCLECI_VERSION.
  if ! SORTED_MIN="$(printf "%s\n%s" "$MIN_CIRCLECI_VERSION" "$THIS_VERSION" | sort -V | head -n1)"; then
    echo "Failed to sort versions. Please open an issue to report this."
    return 1
  fi

  if [ "$THIS_VERSION" != "${THIS_VERSION#$MIN_CIRCLECI_VERSION}" ]; then
    return 0 # OK - Versions have the same prefix, so we consider them equal.
  elif [ "$SORTED_MIN" = "$MIN_CIRCLECI_VERSION" ]; then
    return 0 # OK - MIN_CIRCLECI_VERSION is lower than THIS_VERSION.
  fi

  # Version too low.
  echo "The installed circleci cli v$THIS_VERSION is too old. Please upgrade to at least $MIN_CIRCLECI_VERSION"
  return 1
}

circleci_verify
