// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package storagepacker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Item represents a entry that gets inserted into the storage packer
type Item struct {
	// ID is the UUID to identify the item
	ID string `sentinel:"" protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// message is the contents of the item
	Message              *any.Any `sentinel:"" protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_062eae6dce2c607c, []int{0}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Item) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

// BucketV2 is a construct to hold multiple items within itself. This
// abstraction contains multiple buckets of the same kind within itself and
// shares amont them the items that get inserted. When the bucket as a whole
// gets too big to hold more items, the contained buckets gets pushed out only
// to become independent buckets. Hence, this can grow infinitely in terms of
// storage space for items that get inserted.
type BucketV2 struct {
	// Key is the storage path where the bucket gets stored
	Key string `sentinel:"" protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// Items holds the items contained within this bucket
	Items map[string]*Item `sentinel:"" protobuf:"bytes,2,rep,name=items" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Buckets are the buckets contained within this bucket
	Buckets map[string]*BucketV2 `sentinel:"" protobuf:"bytes,3,rep,name=buckets" json:"buckets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Sharded indicates if the contained buckets are pushed out or not
	Sharded bool `sentinel:"" protobuf:"varint,4,opt,name=sharded" json:"sharded,omitempty"`
	// Size of this bucket in number of bytes
	Size                 int64    `sentinel:"" protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketV2) Reset()         { *m = BucketV2{} }
func (m *BucketV2) String() string { return proto.CompactTextString(m) }
func (*BucketV2) ProtoMessage()    {}
func (*BucketV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_062eae6dce2c607c, []int{1}
}
func (m *BucketV2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketV2.Unmarshal(m, b)
}
func (m *BucketV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketV2.Marshal(b, m, deterministic)
}
func (dst *BucketV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketV2.Merge(dst, src)
}
func (m *BucketV2) XXX_Size() int {
	return xxx_messageInfo_BucketV2.Size(m)
}
func (m *BucketV2) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketV2.DiscardUnknown(m)
}

var xxx_messageInfo_BucketV2 proto.InternalMessageInfo

func (m *BucketV2) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BucketV2) GetItems() map[string]*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *BucketV2) GetBuckets() map[string]*BucketV2 {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *BucketV2) GetSharded() bool {
	if m != nil {
		return m.Sharded
	}
	return false
}

func (m *BucketV2) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Bucket struct {
	Key                  string   `sentinel:"" protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Items                []*Item  `sentinel:"" protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_062eae6dce2c607c, []int{2}
}
func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (dst *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(dst, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Bucket) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "storagepacker.Item")
	proto.RegisterType((*BucketV2)(nil), "storagepacker.BucketV2")
	proto.RegisterMapType((map[string]*BucketV2)(nil), "storagepacker.BucketV2.BucketsEntry")
	proto.RegisterMapType((map[string]*Item)(nil), "storagepacker.BucketV2.ItemsEntry")
	proto.RegisterType((*Bucket)(nil), "storagepacker.Bucket")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_062eae6dce2c607c) }

var fileDescriptor_types_062eae6dce2c607c = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x49, 0xba, 0x5f, 0xbe, 0xa9, 0x48, 0x14, 0x8c, 0x3b, 0x95, 0xe2, 0xa1, 0x1e, 0xcc,
	0x60, 0x5e, 0x86, 0x07, 0x41, 0x61, 0x82, 0x07, 0x2f, 0x11, 0xbc, 0x67, 0xeb, 0xb3, 0x96, 0xfd,
	0xe8, 0x68, 0x52, 0xa1, 0xfe, 0xc5, 0xfe, 0x19, 0xd2, 0x64, 0xc1, 0x4e, 0xba, 0xdb, 0x6b, 0xf3,
	0xfd, 0x7c, 0xf9, 0xe4, 0x05, 0x86, 0xa6, 0xda, 0xa2, 0x16, 0xdb, 0x22, 0x37, 0x39, 0x3b, 0xd1,
	0x26, 0x2f, 0x54, 0x8a, 0x5b, 0xb5, 0x58, 0x62, 0x31, 0xba, 0x4a, 0xf3, 0x3c, 0x5d, 0xe1, 0xd8,
	0x1e, 0xce, 0xcb, 0x8f, 0xb1, 0xda, 0x54, 0x2e, 0x19, 0x3d, 0x43, 0xe7, 0xc5, 0xe0, 0x9a, 0x9d,
	0x02, 0xcd, 0x12, 0x4e, 0x42, 0x12, 0x1f, 0x49, 0x9a, 0x25, 0x4c, 0x40, 0x7f, 0x8d, 0x5a, 0xab,
	0x14, 0x39, 0x0d, 0x49, 0x3c, 0x9c, 0x5c, 0x08, 0x57, 0x22, 0x7c, 0x89, 0x78, 0xdc, 0x54, 0xd2,
	0x87, 0xa2, 0x1f, 0x0a, 0x83, 0xa7, 0x72, 0xb1, 0x44, 0xf3, 0x3e, 0x61, 0x67, 0x10, 0x2c, 0xb1,
	0xda, 0xb5, 0xd5, 0x23, 0x9b, 0x42, 0x37, 0x33, 0xb8, 0xd6, 0x9c, 0x86, 0x41, 0x3c, 0x9c, 0x44,
	0x62, 0x4f, 0x50, 0x78, 0x52, 0xd4, 0x2e, 0x7a, 0xb6, 0x31, 0x45, 0x25, 0x1d, 0xc0, 0x1e, 0xa0,
	0x3f, 0xb7, 0xa7, 0x9a, 0x07, 0x96, 0xbd, 0x3e, 0xc4, 0xba, 0x61, 0x47, 0x7b, 0x88, 0x71, 0xe8,
	0xeb, 0x4f, 0x55, 0x24, 0x98, 0xf0, 0x4e, 0x48, 0xe2, 0x81, 0xf4, 0x9f, 0x8c, 0x41, 0x47, 0x67,
	0xdf, 0xc8, 0xbb, 0x21, 0x89, 0x03, 0x69, 0xe7, 0xd1, 0x2b, 0xc0, 0x9f, 0x42, 0xcb, 0x3d, 0x6e,
	0xa0, 0xfb, 0xa5, 0x56, 0xa5, 0x5f, 0xca, 0xf9, 0x3f, 0x97, 0x9a, 0x95, 0x2e, 0x71, 0x4f, 0xa7,
	0x64, 0xf4, 0x06, 0xc7, 0x4d, 0xab, 0x96, 0xc2, 0xdb, 0xfd, 0xc2, 0xcb, 0x03, 0x97, 0x6b, 0x94,
	0x46, 0x33, 0xe8, 0xb9, 0xdf, 0xed, 0x7e, 0xcd, 0x3d, 0xb7, 0xfb, 0xd9, 0xc4, 0xbc, 0x67, 0x1f,
	0xf2, 0xee, 0x37, 0x00, 0x00, 0xff, 0xff, 0x68, 0xf6, 0x11, 0xaa, 0x39, 0x02, 0x00, 0x00,
}
