export const SELECTORS = {
  issuersCardTitle: '[data-test-selectable-card-container="Issuers"] h3',
  issuersCardSubtitle: '[data-test-selectable-card-container="Issuers"] p',
  issuersCardLink: '[data-test-selectable-card-container="Issuers"] a',
  issuersCardOverviewNum: '[data-test-selectable-card-container="Issuers"] .title-number',
  rolesCardTitle: '[data-test-selectable-card-container="Roles"] h3',
  rolesCardSubtitle: '[data-test-selectable-card-container="Roles"] p',
  rolesCardLink: '[data-test-selectable-card-container="Roles"] a',
  rolesCardOverviewNum: '[data-test-selectable-card-container="Roles"] .title-number',
  issueCertificate: '[data-test-selectable-card-form="issue-certificate"] h3',
  issueCertificateInput: '[data-test-selectable-card-form-input="issue-certificate"] span',
  issueCertificateButton: '[data-test-selectable-card-form-button="issue-certificate"]',
  viewCertificate: '[data-test-selectable-card-form="view-certificate"] h3',
  viewCertificateInput: '[data-test-selectable-card-form-input=view-certificate] span',
  viewCertificateButton: '[data-test-selectable-card-form-button="view-certificate"]',
  firstPowerSelectOption: '[data-option-index="0"]',
};
