export const SELECTORS = {
  issuersCardTitle: '[data-test-selectable-card-container="Issuers"] h3',
  issuersCardSubtitle: '[data-test-selectable-card-container="Issuers"] p',
  issuersCardLink: '[data-test-selectable-card-container="Issuers"] a',
  issuersCardOverviewNum: '[data-test-selectable-card-container="Issuers"] .title-number',
  rolesCardTitle: '[data-test-selectable-card-container="Roles"] h3',
  rolesCardSubtitle: '[data-test-selectable-card-container="Roles"] p',
  rolesCardLink: '[data-test-selectable-card-container="Roles"] a',
  rolesCardOverviewNum: '[data-test-selectable-card-container="Roles"] .title-number',
  issueCertificate: '[data-test-selectable-card-container="Issue certificate"] h3',
  issueCertificateInput: '[data-test-issue-certificate-input]',
  issueCertificatePowerSearch: '[data-test-issue-certificate-input] span',
  issueCertificateButton: '[data-test-issue-certificate-button]',
  viewCertificate: '[data-test-selectable-card-container="View certificate"] h3',
  viewCertificateInput: '[data-test-view-certificate-input]',
  viewCertificatePowerSearch: '[data-test-view-certificate-input] span',
  viewCertificateButton: '[data-test-view-certificate-button]',
  firstPowerSelectOption: '[data-option-index="0"]',
};
