# Copyright IBM Corp. 2016, 2025
# SPDX-License-Identifier: BUSL-1.1


# This action will set up Node and then install pnpm dependencies, which might be restored from cache if available.
# In case of a cache miss, pnpm dependencies will be installed and later be stored in the "post step" of actions/cache.
---
name: Setup pnpm
description: Setup Node and install pnpm
runs:
  using: composite
  steps:

    - name: Install PNPM
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      with:
        run_install: false
        package_json_file: './ui/package.json'

    - name: Setup Node Caching
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: './ui/package.json'
        cache: pnpm
        cache-dependency-path: ui/pnpm-lock.yaml

    - name: Install UI dependencies
      working-directory: ./ui
      shell: bash
      run: |
        pnpm i
        pnpm rebuild node-sass
