---
name: backport-pull-request-ent

# NOTE: Don't ever set up concurrency groups. We never want this workflow to
# be cancelled.

on:
  pull_request_target:
    types:
      - closed
  workflow_dispatch:
    inputs:
      number:
        type: string
        description: The pull request number to copy to enterprise
        required: true

jobs:
  backport-pull-request:
    name: Backport pull request to ce/* and/or release/* branches
    if: github.event.pull_request.merged
    runs-on: [self-hosted, ubuntu-latest-x64]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: main
      - id: vault-auth
        run: vault-auth
      - id: vault-secrets
        uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets: |
            kv/data/github/${{ github.repository }}/github-token token | ELEVATED_GITHUB_TOKEN;
      - id: set-up-pipeline
        uses: ./.github/actions/set-up-pipeline
        with:
          github-token: ${{ steps.vault-secrets.outputs.ELEVATED_GITHUB_TOKEN }}
      - id: create-backport
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.vault-secrets.outputs.ELEVATED_GITHUB_TOKEN }}
        run: |
          pipeline github create backport ${{ runner.debug && '--log debug' }} --recurse 4 ${{ github.event.number || inputs.number }}
