---
name: ensure_build_workflow_succeeded

on:
  # Github's branch protection rules for required workflow checks are a bit
  # cumbersome when you have many jobs. The required checks have to be configured
  # at the workflow job level. As child workflows of build.yml and Enos can be
  # dynamic and change often, there's no way to create or maintain a valid list
  # of workflow checks that need to succeeded in order to merge.
  #
  # To work around this problem we've chosen to trigger this workflow on
  # completion of all the jobs that are triggered by build or build-docs. This
  # workflow inspects the conclusion of the build workflow event and either passes
  # or fails. This allows our branch protection rules for the build workflow to
  # depend only on this workflow succeeding, which can only happen if all child
  # workflows of the build job have succeeded.
  workflow_run:
    workflows: [build, build-docs]
    types: [completed]

jobs:
  ensure-all-build-workflows-succeeded:
    name: Ensure that all workflows spawned by the build workflow succeeded
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion != 'success' }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('One or more workflows spawned by the build job did not succeed. All build job workflows are required to pass before merge')
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "All build and integration workflows have succeeded!"
