---
name: lint-enos

on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  lint:
    # Only run this workflow on pull requests from hashicorp/vault branches
    # as we need secrets to install enos.
    if: "! github.event.pull_request.head.repo.fork"
    name: lint
    runs-on: ${{ github.repository == 'hashicorp/vault' && 'ubuntu-latest' || fromJSON('["self-hosted","ubuntu-22.04-x64","large"]') }}
    permissions:
      actions: read
      contents: read
      id-token: write
      issues: read
      pull-requests: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/metadata
        id: metadata
      - if: steps.metadata.outputs.is-ent-repo == 'true'
        id: vault-auth
        name: Vault Authenticate
        run: vault-auth
      - if: steps.metadata.outputs.is-ent-repo == 'true'
        id: vault-secrets
        name: Fetch Vault Secrets
        uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc # v4.0.0
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets: |
            kv/data/github/${{ github.repository }}/github-token token | ELEVATED_GITHUB_TOKEN;
      - uses: ./.github/actions/changed-files
        id: changed-files
        with:
          github-token: ${{ steps.metadata.outputs.is-ent-repo != 'true' && secrets.ELEVATED_GITHUB_TOKEN || steps.vault-secrets.outputs.ELEVATED_GITHUB_TOKEN }}
      - if: contains(fromJSON(steps.changed-files.outputs.changed-files).groups, 'test_enos')
        id: set-product-version
        uses: hashicorp/actions-set-product-version@d9be602dfa87e201c79a3937c038f19391c9a430 # v2.0.2
        with:
          checkout: false # don't override the reference we've checked out
      - if: contains(fromJSON(steps.changed-files.outputs.changed-files).groups, 'test_enos')
        uses: ./.github/actions/set-up-go
        with:
          no-restore: true
          no-save: true
      - if: contains(fromJSON(steps.changed-files.outputs.changed-files).groups, 'test_enos')
        uses: ./.github/actions/install-tools
      - if: contains(fromJSON(steps.changed-files.outputs.changed-files).groups, 'test_enos')
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false
      - if: contains(fromJSON(steps.changed-files.outputs.changed-files).groups, 'test_enos')
        uses: hashicorp/action-setup-enos@3817610f3f8dc74a8dbe15bc23c6dc3164f9b224 # v1.53
      - if: contains(fromJSON(steps.changed-files.outputs.changed-files).groups, 'test_enos')
        name: Ensure shellcheck is available for linting
        run: which shellcheck || (sudo apt update && sudo apt install -y shellcheck)
      - if: contains(fromJSON(steps.changed-files.outputs.changed-files).groups, 'test_enos')
        name: lint
        working-directory: ./enos
        env:
          ENOS_VAR_vault_product_version: ${{ steps.set-product-version.outputs.product-version }}
        run: make lint
