name: test-go-acceptance-nightly

on:
  # Change to nightly cadence once API-credential-requiring tests are added to the jobs
  workflow_dispatch: 

# cancel existing runs of the same workflow on the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

# Currently the jobs here are only for acceptance tests that have no dependencies except for Docker
jobs:
  plugins-database:
    uses: ./.github/workflows/test-run-acc-tests-for-path.yml
    strategy:
      matrix:
        name: [mongodb, mysql, postgresql]
    with:
      name: plugins-database-${{ matrix.name }}
      path: plugins/database/${{ matrix.name }}

  external:
    uses: ./.github/workflows/test-run-acc-tests-for-path.yml
    strategy:
      matrix:
        name: [api, identity, token]
    with:
      name: external-${{ matrix.name }}
      path: vault/external_tests/${{ matrix.name }}
  
  # Suggestions and tips for adding more acceptance test jobs:
  #   - the job name is up to you, but it should be derived from the path that the tests are found in
  #     - for instance, "plugins-database" is a job for acceptance tests in the plugins/database path
  #   - the path will be used with go test wildcards, but don't include the preceding "./" or following "/..."
  #   - the name parameter is used to construct the log artifact's name, make it something that is related to the path
