# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

---
name: Determine what files have changed on either a pull request or commit.
description: |
  Determine what files have changed on either a pull request or commit.
  Writes the list of files to

inputs:
  github-token:
    description: A preferred Github token to access private modules if necessary.

outputs:
  changed-files:
    description: All of the files that changed.
    value: ${{ steps.changed-files.outputs.changed-files }}

runs:
  using: composite
  steps:
    - id: changed-files-set-up-pipeline
      name: Set up the pipeline tool
      uses: ./.github/actions/set-up-pipeline
      with:
        github-token: ${{ inputs.github-token || github.token }}
    - id: changed-files
      name: Determine the changed files
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token || github.token }}
      run: |
        # Get a list of changed files and write the "changed-files" output to $GITHUB_OUTPUT
        if [ '${{ github.event_name }}' = 'pull_request' ]; then
          pipeline github list changed-files \
            --owner hashicorp \
            --repo '${{ github.event.pull_request.head.repo.name }}' \
            --pr '${{ github.event.pull_request.number }}' \
            --github-output
        else
          pipeline github list changed-files \
            --owner hashicorp \
            --repo '${{ github.event.repository.name }}' \
            --commit '${{ github.event.after && github.event.after || github.event.push.after && github.event.push.after || github.sha }}' \
            --github-output
        fi
